// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corfustorage.proto

#include "corfustorage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace corfustorage {
PROTOBUF_CONSTEXPR Payload::Payload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ack_)*/nullptr
  , /*decltype(_impl_.err_sealed_)*/nullptr
  , /*decltype(_impl_.err_unwritten_)*/nullptr
  , /*decltype(_impl_.err_written_)*/nullptr
  , /*decltype(_impl_.read_)*/nullptr
  , /*decltype(_impl_.seal_)*/nullptr
  , /*decltype(_impl_.err_deleted_)*/nullptr
  , /*decltype(_impl_.packet_type_)*/int64_t{0}} {}
struct PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadDefaultTypeInternal() {}
  union {
    Payload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadDefaultTypeInternal _Payload_default_instance_;
PROTOBUF_CONSTEXPR Ack::Ack(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ack_code_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AckDefaultTypeInternal() {}
  union {
    Ack _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AckDefaultTypeInternal _Ack_default_instance_;
PROTOBUF_CONSTEXPR errSealed::errSealed(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.err_code_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct errSealedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR errSealedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~errSealedDefaultTypeInternal() {}
  union {
    errSealed _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 errSealedDefaultTypeInternal _errSealed_default_instance_;
PROTOBUF_CONSTEXPR errUnwritten::errUnwritten(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.err_code_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct errUnwrittenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR errUnwrittenDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~errUnwrittenDefaultTypeInternal() {}
  union {
    errUnwritten _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 errUnwrittenDefaultTypeInternal _errUnwritten_default_instance_;
PROTOBUF_CONSTEXPR errWritten::errWritten(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.err_code_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct errWrittenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR errWrittenDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~errWrittenDefaultTypeInternal() {}
  union {
    errWritten _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 errWrittenDefaultTypeInternal _errWritten_default_instance_;
PROTOBUF_CONSTEXPR Read::Read(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadDefaultTypeInternal() {}
  union {
    Read _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadDefaultTypeInternal _Read_default_instance_;
PROTOBUF_CONSTEXPR Seal::Seal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.highaddr_)*/int64_t{0}
  , /*decltype(_impl_.sealed_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SealDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SealDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SealDefaultTypeInternal() {}
  union {
    Seal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SealDefaultTypeInternal _Seal_default_instance_;
PROTOBUF_CONSTEXPR errDeleted::errDeleted(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.err_code_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct errDeletedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR errDeletedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~errDeletedDefaultTypeInternal() {}
  union {
    errDeleted _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 errDeletedDefaultTypeInternal _errDeleted_default_instance_;
}  // namespace corfustorage
static ::_pb::Metadata file_level_metadata_corfustorage_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_corfustorage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_corfustorage_2eproto = nullptr;

const uint32_t TableStruct_corfustorage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.packet_type_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.ack_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.err_sealed_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.err_unwritten_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.err_written_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.read_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.seal_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Payload, _impl_.err_deleted_),
  ~0u,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Ack, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Ack, _impl_.ack_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errSealed, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errSealed, _impl_.err_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errUnwritten, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errUnwritten, _impl_.err_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errWritten, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errWritten, _impl_.err_code_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::errWritten, _impl_.content_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Read, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Read, _impl_.content_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Seal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::Seal, _impl_.sealed_),
  PROTOBUF_FIELD_OFFSET(::corfustorage::Seal, _impl_.highaddr_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errDeleted, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfustorage::errDeleted, _impl_.err_code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::corfustorage::Payload)},
  { 22, -1, -1, sizeof(::corfustorage::Ack)},
  { 29, -1, -1, sizeof(::corfustorage::errSealed)},
  { 36, -1, -1, sizeof(::corfustorage::errUnwritten)},
  { 43, -1, -1, sizeof(::corfustorage::errWritten)},
  { 51, -1, -1, sizeof(::corfustorage::Read)},
  { 58, -1, -1, sizeof(::corfustorage::Seal)},
  { 66, -1, -1, sizeof(::corfustorage::errDeleted)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::corfustorage::_Payload_default_instance_._instance,
  &::corfustorage::_Ack_default_instance_._instance,
  &::corfustorage::_errSealed_default_instance_._instance,
  &::corfustorage::_errUnwritten_default_instance_._instance,
  &::corfustorage::_errWritten_default_instance_._instance,
  &::corfustorage::_Read_default_instance_._instance,
  &::corfustorage::_Seal_default_instance_._instance,
  &::corfustorage::_errDeleted_default_instance_._instance,
};

const char descriptor_table_protodef_corfustorage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022corfustorage.proto\022\014corfustorage\"\276\003\n\007P"
  "ayload\022\023\n\013packet_type\030\001 \001(\003\022#\n\003ack\030\002 \001(\013"
  "2\021.corfustorage.AckH\000\210\001\001\0220\n\nerr_sealed\030\003"
  " \001(\0132\027.corfustorage.errSealedH\001\210\001\001\0226\n\rer"
  "r_unwritten\030\004 \001(\0132\032.corfustorage.errUnwr"
  "ittenH\002\210\001\001\0222\n\013err_written\030\005 \001(\0132\030.corfus"
  "torage.errWrittenH\003\210\001\001\022%\n\004read\030\006 \001(\0132\022.c"
  "orfustorage.ReadH\004\210\001\001\022%\n\004seal\030\007 \001(\0132\022.co"
  "rfustorage.SealH\005\210\001\001\0222\n\013err_deleted\030\010 \001("
  "\0132\030.corfustorage.errDeletedH\006\210\001\001B\006\n\004_ack"
  "B\r\n\013_err_sealedB\020\n\016_err_unwrittenB\016\n\014_er"
  "r_writtenB\007\n\005_readB\007\n\005_sealB\016\n\014_err_dele"
  "ted\"\027\n\003Ack\022\020\n\010ack_code\030\001 \001(\010\"\035\n\terrSeale"
  "d\022\020\n\010err_code\030\001 \001(\010\" \n\014errUnwritten\022\020\n\010e"
  "rr_code\030\001 \001(\010\"/\n\nerrWritten\022\020\n\010err_code\030"
  "\001 \001(\010\022\017\n\007content\030\002 \001(\t\"\027\n\004Read\022\017\n\007conten"
  "t\030\002 \001(\t\"(\n\004Seal\022\016\n\006sealed\030\001 \001(\010\022\020\n\010higha"
  "ddr\030\002 \001(\003\"\036\n\nerrDeleted\022\020\n\010err_code\030\001 \001("
  "\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_corfustorage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_corfustorage_2eproto = {
    false, false, 729, descriptor_table_protodef_corfustorage_2eproto,
    "corfustorage.proto",
    &descriptor_table_corfustorage_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_corfustorage_2eproto::offsets,
    file_level_metadata_corfustorage_2eproto, file_level_enum_descriptors_corfustorage_2eproto,
    file_level_service_descriptors_corfustorage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_corfustorage_2eproto_getter() {
  return &descriptor_table_corfustorage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_corfustorage_2eproto(&descriptor_table_corfustorage_2eproto);
namespace corfustorage {

// ===================================================================

class Payload::_Internal {
 public:
  using HasBits = decltype(std::declval<Payload>()._impl_._has_bits_);
  static const ::corfustorage::Ack& ack(const Payload* msg);
  static void set_has_ack(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::corfustorage::errSealed& err_sealed(const Payload* msg);
  static void set_has_err_sealed(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::corfustorage::errUnwritten& err_unwritten(const Payload* msg);
  static void set_has_err_unwritten(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::corfustorage::errWritten& err_written(const Payload* msg);
  static void set_has_err_written(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::corfustorage::Read& read(const Payload* msg);
  static void set_has_read(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::corfustorage::Seal& seal(const Payload* msg);
  static void set_has_seal(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static const ::corfustorage::errDeleted& err_deleted(const Payload* msg);
  static void set_has_err_deleted(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

const ::corfustorage::Ack&
Payload::_Internal::ack(const Payload* msg) {
  return *msg->_impl_.ack_;
}
const ::corfustorage::errSealed&
Payload::_Internal::err_sealed(const Payload* msg) {
  return *msg->_impl_.err_sealed_;
}
const ::corfustorage::errUnwritten&
Payload::_Internal::err_unwritten(const Payload* msg) {
  return *msg->_impl_.err_unwritten_;
}
const ::corfustorage::errWritten&
Payload::_Internal::err_written(const Payload* msg) {
  return *msg->_impl_.err_written_;
}
const ::corfustorage::Read&
Payload::_Internal::read(const Payload* msg) {
  return *msg->_impl_.read_;
}
const ::corfustorage::Seal&
Payload::_Internal::seal(const Payload* msg) {
  return *msg->_impl_.seal_;
}
const ::corfustorage::errDeleted&
Payload::_Internal::err_deleted(const Payload* msg) {
  return *msg->_impl_.err_deleted_;
}
Payload::Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.Payload)
}
Payload::Payload(const Payload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Payload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ack_){nullptr}
    , decltype(_impl_.err_sealed_){nullptr}
    , decltype(_impl_.err_unwritten_){nullptr}
    , decltype(_impl_.err_written_){nullptr}
    , decltype(_impl_.read_){nullptr}
    , decltype(_impl_.seal_){nullptr}
    , decltype(_impl_.err_deleted_){nullptr}
    , decltype(_impl_.packet_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_ack()) {
    _this->_impl_.ack_ = new ::corfustorage::Ack(*from._impl_.ack_);
  }
  if (from._internal_has_err_sealed()) {
    _this->_impl_.err_sealed_ = new ::corfustorage::errSealed(*from._impl_.err_sealed_);
  }
  if (from._internal_has_err_unwritten()) {
    _this->_impl_.err_unwritten_ = new ::corfustorage::errUnwritten(*from._impl_.err_unwritten_);
  }
  if (from._internal_has_err_written()) {
    _this->_impl_.err_written_ = new ::corfustorage::errWritten(*from._impl_.err_written_);
  }
  if (from._internal_has_read()) {
    _this->_impl_.read_ = new ::corfustorage::Read(*from._impl_.read_);
  }
  if (from._internal_has_seal()) {
    _this->_impl_.seal_ = new ::corfustorage::Seal(*from._impl_.seal_);
  }
  if (from._internal_has_err_deleted()) {
    _this->_impl_.err_deleted_ = new ::corfustorage::errDeleted(*from._impl_.err_deleted_);
  }
  _this->_impl_.packet_type_ = from._impl_.packet_type_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.Payload)
}

inline void Payload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ack_){nullptr}
    , decltype(_impl_.err_sealed_){nullptr}
    , decltype(_impl_.err_unwritten_){nullptr}
    , decltype(_impl_.err_written_){nullptr}
    , decltype(_impl_.read_){nullptr}
    , decltype(_impl_.seal_){nullptr}
    , decltype(_impl_.err_deleted_){nullptr}
    , decltype(_impl_.packet_type_){int64_t{0}}
  };
}

Payload::~Payload() {
  // @@protoc_insertion_point(destructor:corfustorage.Payload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Payload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.ack_;
  if (this != internal_default_instance()) delete _impl_.err_sealed_;
  if (this != internal_default_instance()) delete _impl_.err_unwritten_;
  if (this != internal_default_instance()) delete _impl_.err_written_;
  if (this != internal_default_instance()) delete _impl_.read_;
  if (this != internal_default_instance()) delete _impl_.seal_;
  if (this != internal_default_instance()) delete _impl_.err_deleted_;
}

void Payload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.Payload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(_impl_.ack_ != nullptr);
      _impl_.ack_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.err_sealed_ != nullptr);
      _impl_.err_sealed_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.err_unwritten_ != nullptr);
      _impl_.err_unwritten_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(_impl_.err_written_ != nullptr);
      _impl_.err_written_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(_impl_.read_ != nullptr);
      _impl_.read_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(_impl_.seal_ != nullptr);
      _impl_.seal_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(_impl_.err_deleted_ != nullptr);
      _impl_.err_deleted_->Clear();
    }
  }
  _impl_.packet_type_ = int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Payload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 packet_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.packet_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.Ack ack = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.errSealed err_sealed = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_err_sealed(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.errUnwritten err_unwritten = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_err_unwritten(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.errWritten err_written = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_err_written(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.Read read = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_read(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.Seal seal = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_seal(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfustorage.errDeleted err_deleted = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_err_deleted(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Payload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.Payload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_packet_type(), target);
  }

  // optional .corfustorage.Ack ack = 2;
  if (_internal_has_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::ack(this),
        _Internal::ack(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.errSealed err_sealed = 3;
  if (_internal_has_err_sealed()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::err_sealed(this),
        _Internal::err_sealed(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.errUnwritten err_unwritten = 4;
  if (_internal_has_err_unwritten()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::err_unwritten(this),
        _Internal::err_unwritten(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.errWritten err_written = 5;
  if (_internal_has_err_written()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::err_written(this),
        _Internal::err_written(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.Read read = 6;
  if (_internal_has_read()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::read(this),
        _Internal::read(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.Seal seal = 7;
  if (_internal_has_seal()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::seal(this),
        _Internal::seal(this).GetCachedSize(), target, stream);
  }

  // optional .corfustorage.errDeleted err_deleted = 8;
  if (_internal_has_err_deleted()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::err_deleted(this),
        _Internal::err_deleted(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.Payload)
  return target;
}

size_t Payload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.Payload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional .corfustorage.Ack ack = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.ack_);
    }

    // optional .corfustorage.errSealed err_sealed = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.err_sealed_);
    }

    // optional .corfustorage.errUnwritten err_unwritten = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.err_unwritten_);
    }

    // optional .corfustorage.errWritten err_written = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.err_written_);
    }

    // optional .corfustorage.Read read = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.read_);
    }

    // optional .corfustorage.Seal seal = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.seal_);
    }

    // optional .corfustorage.errDeleted err_deleted = 8;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.err_deleted_);
    }

  }
  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_packet_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Payload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Payload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Payload::GetClassData() const { return &_class_data_; }


void Payload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Payload*>(&to_msg);
  auto& from = static_cast<const Payload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.Payload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_ack()->::corfustorage::Ack::MergeFrom(
          from._internal_ack());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_err_sealed()->::corfustorage::errSealed::MergeFrom(
          from._internal_err_sealed());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_err_unwritten()->::corfustorage::errUnwritten::MergeFrom(
          from._internal_err_unwritten());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_err_written()->::corfustorage::errWritten::MergeFrom(
          from._internal_err_written());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_mutable_read()->::corfustorage::Read::MergeFrom(
          from._internal_read());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_mutable_seal()->::corfustorage::Seal::MergeFrom(
          from._internal_seal());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_mutable_err_deleted()->::corfustorage::errDeleted::MergeFrom(
          from._internal_err_deleted());
    }
  }
  if (from._internal_packet_type() != 0) {
    _this->_internal_set_packet_type(from._internal_packet_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Payload::CopyFrom(const Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Payload::IsInitialized() const {
  return true;
}

void Payload::InternalSwap(Payload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Payload, _impl_.packet_type_)
      + sizeof(Payload::_impl_.packet_type_)
      - PROTOBUF_FIELD_OFFSET(Payload, _impl_.ack_)>(
          reinterpret_cast<char*>(&_impl_.ack_),
          reinterpret_cast<char*>(&other->_impl_.ack_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Payload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[0]);
}

// ===================================================================

class Ack::_Internal {
 public:
};

Ack::Ack(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.Ack)
}
Ack::Ack(const Ack& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Ack* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ack_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.ack_code_ = from._impl_.ack_code_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.Ack)
}

inline void Ack::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ack_code_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Ack::~Ack() {
  // @@protoc_insertion_point(destructor:corfustorage.Ack)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ack::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ack::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.Ack)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ack_code_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ack::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ack_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ack_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ack::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.Ack)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ack_code = 1;
  if (this->_internal_ack_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ack_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.Ack)
  return target;
}

size_t Ack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.Ack)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ack_code = 1;
  if (this->_internal_ack_code() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ack::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Ack::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ack::GetClassData() const { return &_class_data_; }


void Ack::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Ack*>(&to_msg);
  auto& from = static_cast<const Ack&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.Ack)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ack_code() != 0) {
    _this->_internal_set_ack_code(from._internal_ack_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ack::CopyFrom(const Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ack::IsInitialized() const {
  return true;
}

void Ack::InternalSwap(Ack* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.ack_code_, other->_impl_.ack_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Ack::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[1]);
}

// ===================================================================

class errSealed::_Internal {
 public:
};

errSealed::errSealed(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.errSealed)
}
errSealed::errSealed(const errSealed& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  errSealed* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.err_code_ = from._impl_.err_code_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.errSealed)
}

inline void errSealed::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

errSealed::~errSealed() {
  // @@protoc_insertion_point(destructor:corfustorage.errSealed)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void errSealed::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void errSealed::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void errSealed::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.errSealed)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.err_code_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* errSealed::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool err_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.err_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* errSealed::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.errSealed)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_err_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.errSealed)
  return target;
}

size_t errSealed::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.errSealed)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData errSealed::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    errSealed::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*errSealed::GetClassData() const { return &_class_data_; }


void errSealed::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<errSealed*>(&to_msg);
  auto& from = static_cast<const errSealed&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.errSealed)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_err_code() != 0) {
    _this->_internal_set_err_code(from._internal_err_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void errSealed::CopyFrom(const errSealed& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.errSealed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool errSealed::IsInitialized() const {
  return true;
}

void errSealed::InternalSwap(errSealed* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.err_code_, other->_impl_.err_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata errSealed::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[2]);
}

// ===================================================================

class errUnwritten::_Internal {
 public:
};

errUnwritten::errUnwritten(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.errUnwritten)
}
errUnwritten::errUnwritten(const errUnwritten& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  errUnwritten* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.err_code_ = from._impl_.err_code_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.errUnwritten)
}

inline void errUnwritten::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

errUnwritten::~errUnwritten() {
  // @@protoc_insertion_point(destructor:corfustorage.errUnwritten)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void errUnwritten::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void errUnwritten::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void errUnwritten::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.errUnwritten)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.err_code_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* errUnwritten::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool err_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.err_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* errUnwritten::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.errUnwritten)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_err_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.errUnwritten)
  return target;
}

size_t errUnwritten::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.errUnwritten)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData errUnwritten::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    errUnwritten::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*errUnwritten::GetClassData() const { return &_class_data_; }


void errUnwritten::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<errUnwritten*>(&to_msg);
  auto& from = static_cast<const errUnwritten&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.errUnwritten)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_err_code() != 0) {
    _this->_internal_set_err_code(from._internal_err_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void errUnwritten::CopyFrom(const errUnwritten& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.errUnwritten)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool errUnwritten::IsInitialized() const {
  return true;
}

void errUnwritten::InternalSwap(errUnwritten* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.err_code_, other->_impl_.err_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata errUnwritten::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[3]);
}

// ===================================================================

class errWritten::_Internal {
 public:
};

errWritten::errWritten(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.errWritten)
}
errWritten::errWritten(const errWritten& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  errWritten* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.err_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.err_code_ = from._impl_.err_code_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.errWritten)
}

inline void errWritten::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.err_code_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

errWritten::~errWritten() {
  // @@protoc_insertion_point(destructor:corfustorage.errWritten)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void errWritten::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
}

void errWritten::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void errWritten::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.errWritten)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.err_code_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* errWritten::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool err_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.err_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string content = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "corfustorage.errWritten.content"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* errWritten::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.errWritten)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_err_code(), target);
  }

  // string content = 2;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "corfustorage.errWritten.content");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.errWritten)
  return target;
}

size_t errWritten::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.errWritten)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData errWritten::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    errWritten::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*errWritten::GetClassData() const { return &_class_data_; }


void errWritten::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<errWritten*>(&to_msg);
  auto& from = static_cast<const errWritten&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.errWritten)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_err_code() != 0) {
    _this->_internal_set_err_code(from._internal_err_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void errWritten::CopyFrom(const errWritten& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.errWritten)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool errWritten::IsInitialized() const {
  return true;
}

void errWritten::InternalSwap(errWritten* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  swap(_impl_.err_code_, other->_impl_.err_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata errWritten::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[4]);
}

// ===================================================================

class Read::_Internal {
 public:
};

Read::Read(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.Read)
}
Read::Read(const Read& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Read* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:corfustorage.Read)
}

inline void Read::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Read::~Read() {
  // @@protoc_insertion_point(destructor:corfustorage.Read)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Read::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
}

void Read::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Read::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.Read)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Read::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string content = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "corfustorage.Read.content"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Read::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.Read)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 2;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "corfustorage.Read.content");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.Read)
  return target;
}

size_t Read::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.Read)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Read::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Read::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Read::GetClassData() const { return &_class_data_; }


void Read::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Read*>(&to_msg);
  auto& from = static_cast<const Read&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.Read)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Read::CopyFrom(const Read& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.Read)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Read::IsInitialized() const {
  return true;
}

void Read::InternalSwap(Read* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Read::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[5]);
}

// ===================================================================

class Seal::_Internal {
 public:
};

Seal::Seal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.Seal)
}
Seal::Seal(const Seal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Seal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.highaddr_){}
    , decltype(_impl_.sealed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.highaddr_, &from._impl_.highaddr_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sealed_) -
    reinterpret_cast<char*>(&_impl_.highaddr_)) + sizeof(_impl_.sealed_));
  // @@protoc_insertion_point(copy_constructor:corfustorage.Seal)
}

inline void Seal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.highaddr_){int64_t{0}}
    , decltype(_impl_.sealed_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Seal::~Seal() {
  // @@protoc_insertion_point(destructor:corfustorage.Seal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Seal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Seal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Seal::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.Seal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.highaddr_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sealed_) -
      reinterpret_cast<char*>(&_impl_.highaddr_)) + sizeof(_impl_.sealed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Seal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool sealed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.sealed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 highaddr = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.highaddr_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Seal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.Seal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool sealed = 1;
  if (this->_internal_sealed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_sealed(), target);
  }

  // int64 highaddr = 2;
  if (this->_internal_highaddr() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_highaddr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.Seal)
  return target;
}

size_t Seal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.Seal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 highaddr = 2;
  if (this->_internal_highaddr() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_highaddr());
  }

  // bool sealed = 1;
  if (this->_internal_sealed() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Seal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Seal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Seal::GetClassData() const { return &_class_data_; }


void Seal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Seal*>(&to_msg);
  auto& from = static_cast<const Seal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.Seal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_highaddr() != 0) {
    _this->_internal_set_highaddr(from._internal_highaddr());
  }
  if (from._internal_sealed() != 0) {
    _this->_internal_set_sealed(from._internal_sealed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Seal::CopyFrom(const Seal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.Seal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Seal::IsInitialized() const {
  return true;
}

void Seal::InternalSwap(Seal* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Seal, _impl_.sealed_)
      + sizeof(Seal::_impl_.sealed_)
      - PROTOBUF_FIELD_OFFSET(Seal, _impl_.highaddr_)>(
          reinterpret_cast<char*>(&_impl_.highaddr_),
          reinterpret_cast<char*>(&other->_impl_.highaddr_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Seal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[6]);
}

// ===================================================================

class errDeleted::_Internal {
 public:
};

errDeleted::errDeleted(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfustorage.errDeleted)
}
errDeleted::errDeleted(const errDeleted& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  errDeleted* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.err_code_ = from._impl_.err_code_;
  // @@protoc_insertion_point(copy_constructor:corfustorage.errDeleted)
}

inline void errDeleted::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.err_code_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

errDeleted::~errDeleted() {
  // @@protoc_insertion_point(destructor:corfustorage.errDeleted)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void errDeleted::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void errDeleted::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void errDeleted::Clear() {
// @@protoc_insertion_point(message_clear_start:corfustorage.errDeleted)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.err_code_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* errDeleted::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool err_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.err_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* errDeleted::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfustorage.errDeleted)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_err_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfustorage.errDeleted)
  return target;
}

size_t errDeleted::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfustorage.errDeleted)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool err_code = 1;
  if (this->_internal_err_code() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData errDeleted::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    errDeleted::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*errDeleted::GetClassData() const { return &_class_data_; }


void errDeleted::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<errDeleted*>(&to_msg);
  auto& from = static_cast<const errDeleted&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfustorage.errDeleted)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_err_code() != 0) {
    _this->_internal_set_err_code(from._internal_err_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void errDeleted::CopyFrom(const errDeleted& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfustorage.errDeleted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool errDeleted::IsInitialized() const {
  return true;
}

void errDeleted::InternalSwap(errDeleted* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.err_code_, other->_impl_.err_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata errDeleted::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfustorage_2eproto_getter, &descriptor_table_corfustorage_2eproto_once,
      file_level_metadata_corfustorage_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace corfustorage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::corfustorage::Payload*
Arena::CreateMaybeMessage< ::corfustorage::Payload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::Payload >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::Ack*
Arena::CreateMaybeMessage< ::corfustorage::Ack >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::Ack >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::errSealed*
Arena::CreateMaybeMessage< ::corfustorage::errSealed >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::errSealed >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::errUnwritten*
Arena::CreateMaybeMessage< ::corfustorage::errUnwritten >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::errUnwritten >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::errWritten*
Arena::CreateMaybeMessage< ::corfustorage::errWritten >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::errWritten >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::Read*
Arena::CreateMaybeMessage< ::corfustorage::Read >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::Read >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::Seal*
Arena::CreateMaybeMessage< ::corfustorage::Seal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::Seal >(arena);
}
template<> PROTOBUF_NOINLINE ::corfustorage::errDeleted*
Arena::CreateMaybeMessage< ::corfustorage::errDeleted >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfustorage::errDeleted >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
