// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corfuclient.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_corfuclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_corfuclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_corfuclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_corfuclient_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_corfuclient_2eproto;
namespace corfuclient {
class Append;
struct AppendDefaultTypeInternal;
extern AppendDefaultTypeInternal _Append_default_instance_;
class GetToken;
struct GetTokenDefaultTypeInternal;
extern GetTokenDefaultTypeInternal _GetToken_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class Read;
struct ReadDefaultTypeInternal;
extern ReadDefaultTypeInternal _Read_default_instance_;
class Seal;
struct SealDefaultTypeInternal;
extern SealDefaultTypeInternal _Seal_default_instance_;
class Trim;
struct TrimDefaultTypeInternal;
extern TrimDefaultTypeInternal _Trim_default_instance_;
}  // namespace corfuclient
PROTOBUF_NAMESPACE_OPEN
template<> ::corfuclient::Append* Arena::CreateMaybeMessage<::corfuclient::Append>(Arena*);
template<> ::corfuclient::GetToken* Arena::CreateMaybeMessage<::corfuclient::GetToken>(Arena*);
template<> ::corfuclient::Payload* Arena::CreateMaybeMessage<::corfuclient::Payload>(Arena*);
template<> ::corfuclient::Read* Arena::CreateMaybeMessage<::corfuclient::Read>(Arena*);
template<> ::corfuclient::Seal* Arena::CreateMaybeMessage<::corfuclient::Seal>(Arena*);
template<> ::corfuclient::Trim* Arena::CreateMaybeMessage<::corfuclient::Trim>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace corfuclient {

// ===================================================================

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Payload& from) {
    Payload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIDFieldNumber = 6,
    kAppendFieldNumber = 2,
    kReadFieldNumber = 3,
    kTrimFieldNumber = 4,
    kTokenReqFieldNumber = 5,
    kSealFieldNumber = 7,
    kPacketTypeFieldNumber = 1,
  };
  // string clientID = 6;
  void clear_clientid();
  const std::string& clientid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clientid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* clientid);
  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const std::string& value);
  std::string* _internal_mutable_clientid();
  public:

  // optional .corfuclient.Append append = 2;
  bool has_append() const;
  private:
  bool _internal_has_append() const;
  public:
  void clear_append();
  const ::corfuclient::Append& append() const;
  PROTOBUF_NODISCARD ::corfuclient::Append* release_append();
  ::corfuclient::Append* mutable_append();
  void set_allocated_append(::corfuclient::Append* append);
  private:
  const ::corfuclient::Append& _internal_append() const;
  ::corfuclient::Append* _internal_mutable_append();
  public:
  void unsafe_arena_set_allocated_append(
      ::corfuclient::Append* append);
  ::corfuclient::Append* unsafe_arena_release_append();

  // optional .corfuclient.Read read = 3;
  bool has_read() const;
  private:
  bool _internal_has_read() const;
  public:
  void clear_read();
  const ::corfuclient::Read& read() const;
  PROTOBUF_NODISCARD ::corfuclient::Read* release_read();
  ::corfuclient::Read* mutable_read();
  void set_allocated_read(::corfuclient::Read* read);
  private:
  const ::corfuclient::Read& _internal_read() const;
  ::corfuclient::Read* _internal_mutable_read();
  public:
  void unsafe_arena_set_allocated_read(
      ::corfuclient::Read* read);
  ::corfuclient::Read* unsafe_arena_release_read();

  // optional .corfuclient.Trim trim = 4;
  bool has_trim() const;
  private:
  bool _internal_has_trim() const;
  public:
  void clear_trim();
  const ::corfuclient::Trim& trim() const;
  PROTOBUF_NODISCARD ::corfuclient::Trim* release_trim();
  ::corfuclient::Trim* mutable_trim();
  void set_allocated_trim(::corfuclient::Trim* trim);
  private:
  const ::corfuclient::Trim& _internal_trim() const;
  ::corfuclient::Trim* _internal_mutable_trim();
  public:
  void unsafe_arena_set_allocated_trim(
      ::corfuclient::Trim* trim);
  ::corfuclient::Trim* unsafe_arena_release_trim();

  // optional .corfuclient.GetToken token_req = 5;
  bool has_token_req() const;
  private:
  bool _internal_has_token_req() const;
  public:
  void clear_token_req();
  const ::corfuclient::GetToken& token_req() const;
  PROTOBUF_NODISCARD ::corfuclient::GetToken* release_token_req();
  ::corfuclient::GetToken* mutable_token_req();
  void set_allocated_token_req(::corfuclient::GetToken* token_req);
  private:
  const ::corfuclient::GetToken& _internal_token_req() const;
  ::corfuclient::GetToken* _internal_mutable_token_req();
  public:
  void unsafe_arena_set_allocated_token_req(
      ::corfuclient::GetToken* token_req);
  ::corfuclient::GetToken* unsafe_arena_release_token_req();

  // optional .corfuclient.Seal seal = 7;
  bool has_seal() const;
  private:
  bool _internal_has_seal() const;
  public:
  void clear_seal();
  const ::corfuclient::Seal& seal() const;
  PROTOBUF_NODISCARD ::corfuclient::Seal* release_seal();
  ::corfuclient::Seal* mutable_seal();
  void set_allocated_seal(::corfuclient::Seal* seal);
  private:
  const ::corfuclient::Seal& _internal_seal() const;
  ::corfuclient::Seal* _internal_mutable_seal();
  public:
  void unsafe_arena_set_allocated_seal(
      ::corfuclient::Seal* seal);
  ::corfuclient::Seal* unsafe_arena_release_seal();

  // int64 packet_type = 1;
  void clear_packet_type();
  int64_t packet_type() const;
  void set_packet_type(int64_t value);
  private:
  int64_t _internal_packet_type() const;
  void _internal_set_packet_type(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clientid_;
    ::corfuclient::Append* append_;
    ::corfuclient::Read* read_;
    ::corfuclient::Trim* trim_;
    ::corfuclient::GetToken* token_req_;
    ::corfuclient::Seal* seal_;
    int64_t packet_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// -------------------------------------------------------------------

class Append final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.Append) */ {
 public:
  inline Append() : Append(nullptr) {}
  ~Append() override;
  explicit PROTOBUF_CONSTEXPR Append(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Append(const Append& from);
  Append(Append&& from) noexcept
    : Append() {
    *this = ::std::move(from);
  }

  inline Append& operator=(const Append& from) {
    CopyFrom(from);
    return *this;
  }
  inline Append& operator=(Append&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Append& default_instance() {
    return *internal_default_instance();
  }
  static inline const Append* internal_default_instance() {
    return reinterpret_cast<const Append*>(
               &_Append_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Append& a, Append& b) {
    a.Swap(&b);
  }
  inline void Swap(Append* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Append* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Append* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Append>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Append& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Append& from) {
    Append::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Append* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.Append";
  }
  protected:
  explicit Append(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntryFieldNumber = 2,
    kIdxFieldNumber = 1,
    kCurrEpochFieldNumber = 3,
  };
  // string entry = 2;
  void clear_entry();
  const std::string& entry() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_entry(ArgT0&& arg0, ArgT... args);
  std::string* mutable_entry();
  PROTOBUF_NODISCARD std::string* release_entry();
  void set_allocated_entry(std::string* entry);
  private:
  const std::string& _internal_entry() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_entry(const std::string& value);
  std::string* _internal_mutable_entry();
  public:

  // int64 idx = 1;
  void clear_idx();
  int64_t idx() const;
  void set_idx(int64_t value);
  private:
  int64_t _internal_idx() const;
  void _internal_set_idx(int64_t value);
  public:

  // int64 currEpoch = 3;
  void clear_currepoch();
  int64_t currepoch() const;
  void set_currepoch(int64_t value);
  private:
  int64_t _internal_currepoch() const;
  void _internal_set_currepoch(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.Append)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr entry_;
    int64_t idx_;
    int64_t currepoch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// -------------------------------------------------------------------

class Read final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.Read) */ {
 public:
  inline Read() : Read(nullptr) {}
  ~Read() override;
  explicit PROTOBUF_CONSTEXPR Read(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Read(const Read& from);
  Read(Read&& from) noexcept
    : Read() {
    *this = ::std::move(from);
  }

  inline Read& operator=(const Read& from) {
    CopyFrom(from);
    return *this;
  }
  inline Read& operator=(Read&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Read& default_instance() {
    return *internal_default_instance();
  }
  static inline const Read* internal_default_instance() {
    return reinterpret_cast<const Read*>(
               &_Read_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Read& a, Read& b) {
    a.Swap(&b);
  }
  inline void Swap(Read* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Read* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Read* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Read>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Read& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Read& from) {
    Read::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Read* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.Read";
  }
  protected:
  explicit Read(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdxFieldNumber = 1,
    kCurrEpochFieldNumber = 2,
  };
  // int64 idx = 1;
  void clear_idx();
  int64_t idx() const;
  void set_idx(int64_t value);
  private:
  int64_t _internal_idx() const;
  void _internal_set_idx(int64_t value);
  public:

  // int64 currEpoch = 2;
  void clear_currepoch();
  int64_t currepoch() const;
  void set_currepoch(int64_t value);
  private:
  int64_t _internal_currepoch() const;
  void _internal_set_currepoch(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.Read)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t idx_;
    int64_t currepoch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// -------------------------------------------------------------------

class Trim final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.Trim) */ {
 public:
  inline Trim() : Trim(nullptr) {}
  ~Trim() override;
  explicit PROTOBUF_CONSTEXPR Trim(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Trim(const Trim& from);
  Trim(Trim&& from) noexcept
    : Trim() {
    *this = ::std::move(from);
  }

  inline Trim& operator=(const Trim& from) {
    CopyFrom(from);
    return *this;
  }
  inline Trim& operator=(Trim&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Trim& default_instance() {
    return *internal_default_instance();
  }
  static inline const Trim* internal_default_instance() {
    return reinterpret_cast<const Trim*>(
               &_Trim_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Trim& a, Trim& b) {
    a.Swap(&b);
  }
  inline void Swap(Trim* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Trim* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Trim* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Trim>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Trim& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Trim& from) {
    Trim::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trim* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.Trim";
  }
  protected:
  explicit Trim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdxFieldNumber = 1,
  };
  // int64 idx = 1;
  void clear_idx();
  int64_t idx() const;
  void set_idx(int64_t value);
  private:
  int64_t _internal_idx() const;
  void _internal_set_idx(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.Trim)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t idx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// -------------------------------------------------------------------

class Seal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.Seal) */ {
 public:
  inline Seal() : Seal(nullptr) {}
  ~Seal() override;
  explicit PROTOBUF_CONSTEXPR Seal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Seal(const Seal& from);
  Seal(Seal&& from) noexcept
    : Seal() {
    *this = ::std::move(from);
  }

  inline Seal& operator=(const Seal& from) {
    CopyFrom(from);
    return *this;
  }
  inline Seal& operator=(Seal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Seal& default_instance() {
    return *internal_default_instance();
  }
  static inline const Seal* internal_default_instance() {
    return reinterpret_cast<const Seal*>(
               &_Seal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Seal& a, Seal& b) {
    a.Swap(&b);
  }
  inline void Swap(Seal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Seal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Seal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Seal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Seal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Seal& from) {
    Seal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Seal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.Seal";
  }
  protected:
  explicit Seal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCurrEpochFieldNumber = 1,
  };
  // int64 currEpoch = 1;
  void clear_currepoch();
  int64_t currepoch() const;
  void set_currepoch(int64_t value);
  private:
  int64_t _internal_currepoch() const;
  void _internal_set_currepoch(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.Seal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t currepoch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// -------------------------------------------------------------------

class GetToken final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfuclient.GetToken) */ {
 public:
  inline GetToken() : GetToken(nullptr) {}
  ~GetToken() override;
  explicit PROTOBUF_CONSTEXPR GetToken(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetToken(const GetToken& from);
  GetToken(GetToken&& from) noexcept
    : GetToken() {
    *this = ::std::move(from);
  }

  inline GetToken& operator=(const GetToken& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetToken& operator=(GetToken&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetToken& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetToken* internal_default_instance() {
    return reinterpret_cast<const GetToken*>(
               &_GetToken_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetToken& a, GetToken& b) {
    a.Swap(&b);
  }
  inline void Swap(GetToken* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetToken* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetToken* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetToken>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetToken& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetToken& from) {
    GetToken::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetToken* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfuclient.GetToken";
  }
  protected:
  explicit GetToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqTokenFieldNumber = 1,
  };
  // bool reqToken = 1;
  void clear_reqtoken();
  bool reqtoken() const;
  void set_reqtoken(bool value);
  private:
  bool _internal_reqtoken() const;
  void _internal_set_reqtoken(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfuclient.GetToken)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool reqtoken_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_corfuclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Payload

// int64 packet_type = 1;
inline void Payload::clear_packet_type() {
  _impl_.packet_type_ = int64_t{0};
}
inline int64_t Payload::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline int64_t Payload::packet_type() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.packet_type)
  return _internal_packet_type();
}
inline void Payload::_internal_set_packet_type(int64_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Payload::set_packet_type(int64_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:corfuclient.Payload.packet_type)
}

// optional .corfuclient.Append append = 2;
inline bool Payload::_internal_has_append() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.append_ != nullptr);
  return value;
}
inline bool Payload::has_append() const {
  return _internal_has_append();
}
inline void Payload::clear_append() {
  if (_impl_.append_ != nullptr) _impl_.append_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::corfuclient::Append& Payload::_internal_append() const {
  const ::corfuclient::Append* p = _impl_.append_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfuclient::Append&>(
      ::corfuclient::_Append_default_instance_);
}
inline const ::corfuclient::Append& Payload::append() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.append)
  return _internal_append();
}
inline void Payload::unsafe_arena_set_allocated_append(
    ::corfuclient::Append* append) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.append_);
  }
  _impl_.append_ = append;
  if (append) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfuclient.Payload.append)
}
inline ::corfuclient::Append* Payload::release_append() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfuclient::Append* temp = _impl_.append_;
  _impl_.append_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfuclient::Append* Payload::unsafe_arena_release_append() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.append)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfuclient::Append* temp = _impl_.append_;
  _impl_.append_ = nullptr;
  return temp;
}
inline ::corfuclient::Append* Payload::_internal_mutable_append() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.append_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfuclient::Append>(GetArenaForAllocation());
    _impl_.append_ = p;
  }
  return _impl_.append_;
}
inline ::corfuclient::Append* Payload::mutable_append() {
  ::corfuclient::Append* _msg = _internal_mutable_append();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.append)
  return _msg;
}
inline void Payload::set_allocated_append(::corfuclient::Append* append) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.append_;
  }
  if (append) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(append);
    if (message_arena != submessage_arena) {
      append = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, append, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.append_ = append;
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.append)
}

// optional .corfuclient.Read read = 3;
inline bool Payload::_internal_has_read() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.read_ != nullptr);
  return value;
}
inline bool Payload::has_read() const {
  return _internal_has_read();
}
inline void Payload::clear_read() {
  if (_impl_.read_ != nullptr) _impl_.read_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::corfuclient::Read& Payload::_internal_read() const {
  const ::corfuclient::Read* p = _impl_.read_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfuclient::Read&>(
      ::corfuclient::_Read_default_instance_);
}
inline const ::corfuclient::Read& Payload::read() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.read)
  return _internal_read();
}
inline void Payload::unsafe_arena_set_allocated_read(
    ::corfuclient::Read* read) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.read_);
  }
  _impl_.read_ = read;
  if (read) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfuclient.Payload.read)
}
inline ::corfuclient::Read* Payload::release_read() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::corfuclient::Read* temp = _impl_.read_;
  _impl_.read_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfuclient::Read* Payload::unsafe_arena_release_read() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.read)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::corfuclient::Read* temp = _impl_.read_;
  _impl_.read_ = nullptr;
  return temp;
}
inline ::corfuclient::Read* Payload::_internal_mutable_read() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.read_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfuclient::Read>(GetArenaForAllocation());
    _impl_.read_ = p;
  }
  return _impl_.read_;
}
inline ::corfuclient::Read* Payload::mutable_read() {
  ::corfuclient::Read* _msg = _internal_mutable_read();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.read)
  return _msg;
}
inline void Payload::set_allocated_read(::corfuclient::Read* read) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.read_;
  }
  if (read) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(read);
    if (message_arena != submessage_arena) {
      read = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, read, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.read_ = read;
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.read)
}

// optional .corfuclient.Trim trim = 4;
inline bool Payload::_internal_has_trim() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.trim_ != nullptr);
  return value;
}
inline bool Payload::has_trim() const {
  return _internal_has_trim();
}
inline void Payload::clear_trim() {
  if (_impl_.trim_ != nullptr) _impl_.trim_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::corfuclient::Trim& Payload::_internal_trim() const {
  const ::corfuclient::Trim* p = _impl_.trim_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfuclient::Trim&>(
      ::corfuclient::_Trim_default_instance_);
}
inline const ::corfuclient::Trim& Payload::trim() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.trim)
  return _internal_trim();
}
inline void Payload::unsafe_arena_set_allocated_trim(
    ::corfuclient::Trim* trim) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.trim_);
  }
  _impl_.trim_ = trim;
  if (trim) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfuclient.Payload.trim)
}
inline ::corfuclient::Trim* Payload::release_trim() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::corfuclient::Trim* temp = _impl_.trim_;
  _impl_.trim_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfuclient::Trim* Payload::unsafe_arena_release_trim() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.trim)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::corfuclient::Trim* temp = _impl_.trim_;
  _impl_.trim_ = nullptr;
  return temp;
}
inline ::corfuclient::Trim* Payload::_internal_mutable_trim() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.trim_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfuclient::Trim>(GetArenaForAllocation());
    _impl_.trim_ = p;
  }
  return _impl_.trim_;
}
inline ::corfuclient::Trim* Payload::mutable_trim() {
  ::corfuclient::Trim* _msg = _internal_mutable_trim();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.trim)
  return _msg;
}
inline void Payload::set_allocated_trim(::corfuclient::Trim* trim) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.trim_;
  }
  if (trim) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(trim);
    if (message_arena != submessage_arena) {
      trim = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, trim, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.trim_ = trim;
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.trim)
}

// optional .corfuclient.GetToken token_req = 5;
inline bool Payload::_internal_has_token_req() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.token_req_ != nullptr);
  return value;
}
inline bool Payload::has_token_req() const {
  return _internal_has_token_req();
}
inline void Payload::clear_token_req() {
  if (_impl_.token_req_ != nullptr) _impl_.token_req_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::corfuclient::GetToken& Payload::_internal_token_req() const {
  const ::corfuclient::GetToken* p = _impl_.token_req_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfuclient::GetToken&>(
      ::corfuclient::_GetToken_default_instance_);
}
inline const ::corfuclient::GetToken& Payload::token_req() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.token_req)
  return _internal_token_req();
}
inline void Payload::unsafe_arena_set_allocated_token_req(
    ::corfuclient::GetToken* token_req) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.token_req_);
  }
  _impl_.token_req_ = token_req;
  if (token_req) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfuclient.Payload.token_req)
}
inline ::corfuclient::GetToken* Payload::release_token_req() {
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::corfuclient::GetToken* temp = _impl_.token_req_;
  _impl_.token_req_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfuclient::GetToken* Payload::unsafe_arena_release_token_req() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.token_req)
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::corfuclient::GetToken* temp = _impl_.token_req_;
  _impl_.token_req_ = nullptr;
  return temp;
}
inline ::corfuclient::GetToken* Payload::_internal_mutable_token_req() {
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.token_req_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfuclient::GetToken>(GetArenaForAllocation());
    _impl_.token_req_ = p;
  }
  return _impl_.token_req_;
}
inline ::corfuclient::GetToken* Payload::mutable_token_req() {
  ::corfuclient::GetToken* _msg = _internal_mutable_token_req();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.token_req)
  return _msg;
}
inline void Payload::set_allocated_token_req(::corfuclient::GetToken* token_req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.token_req_;
  }
  if (token_req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(token_req);
    if (message_arena != submessage_arena) {
      token_req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, token_req, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.token_req_ = token_req;
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.token_req)
}

// string clientID = 6;
inline void Payload::clear_clientid() {
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& Payload::clientid() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.clientID)
  return _internal_clientid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Payload::set_clientid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.clientid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corfuclient.Payload.clientID)
}
inline std::string* Payload::mutable_clientid() {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.clientID)
  return _s;
}
inline const std::string& Payload::_internal_clientid() const {
  return _impl_.clientid_.Get();
}
inline void Payload::_internal_set_clientid(const std::string& value) {
  
  _impl_.clientid_.Set(value, GetArenaForAllocation());
}
inline std::string* Payload::_internal_mutable_clientid() {
  
  return _impl_.clientid_.Mutable(GetArenaForAllocation());
}
inline std::string* Payload::release_clientid() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.clientID)
  return _impl_.clientid_.Release();
}
inline void Payload::set_allocated_clientid(std::string* clientid) {
  if (clientid != nullptr) {
    
  } else {
    
  }
  _impl_.clientid_.SetAllocated(clientid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.clientID)
}

// optional .corfuclient.Seal seal = 7;
inline bool Payload::_internal_has_seal() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.seal_ != nullptr);
  return value;
}
inline bool Payload::has_seal() const {
  return _internal_has_seal();
}
inline void Payload::clear_seal() {
  if (_impl_.seal_ != nullptr) _impl_.seal_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::corfuclient::Seal& Payload::_internal_seal() const {
  const ::corfuclient::Seal* p = _impl_.seal_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfuclient::Seal&>(
      ::corfuclient::_Seal_default_instance_);
}
inline const ::corfuclient::Seal& Payload::seal() const {
  // @@protoc_insertion_point(field_get:corfuclient.Payload.seal)
  return _internal_seal();
}
inline void Payload::unsafe_arena_set_allocated_seal(
    ::corfuclient::Seal* seal) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.seal_);
  }
  _impl_.seal_ = seal;
  if (seal) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfuclient.Payload.seal)
}
inline ::corfuclient::Seal* Payload::release_seal() {
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::corfuclient::Seal* temp = _impl_.seal_;
  _impl_.seal_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfuclient::Seal* Payload::unsafe_arena_release_seal() {
  // @@protoc_insertion_point(field_release:corfuclient.Payload.seal)
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::corfuclient::Seal* temp = _impl_.seal_;
  _impl_.seal_ = nullptr;
  return temp;
}
inline ::corfuclient::Seal* Payload::_internal_mutable_seal() {
  _impl_._has_bits_[0] |= 0x00000010u;
  if (_impl_.seal_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfuclient::Seal>(GetArenaForAllocation());
    _impl_.seal_ = p;
  }
  return _impl_.seal_;
}
inline ::corfuclient::Seal* Payload::mutable_seal() {
  ::corfuclient::Seal* _msg = _internal_mutable_seal();
  // @@protoc_insertion_point(field_mutable:corfuclient.Payload.seal)
  return _msg;
}
inline void Payload::set_allocated_seal(::corfuclient::Seal* seal) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.seal_;
  }
  if (seal) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(seal);
    if (message_arena != submessage_arena) {
      seal = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, seal, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.seal_ = seal;
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Payload.seal)
}

// -------------------------------------------------------------------

// Append

// int64 idx = 1;
inline void Append::clear_idx() {
  _impl_.idx_ = int64_t{0};
}
inline int64_t Append::_internal_idx() const {
  return _impl_.idx_;
}
inline int64_t Append::idx() const {
  // @@protoc_insertion_point(field_get:corfuclient.Append.idx)
  return _internal_idx();
}
inline void Append::_internal_set_idx(int64_t value) {
  
  _impl_.idx_ = value;
}
inline void Append::set_idx(int64_t value) {
  _internal_set_idx(value);
  // @@protoc_insertion_point(field_set:corfuclient.Append.idx)
}

// string entry = 2;
inline void Append::clear_entry() {
  _impl_.entry_.ClearToEmpty();
}
inline const std::string& Append::entry() const {
  // @@protoc_insertion_point(field_get:corfuclient.Append.entry)
  return _internal_entry();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Append::set_entry(ArgT0&& arg0, ArgT... args) {
 
 _impl_.entry_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corfuclient.Append.entry)
}
inline std::string* Append::mutable_entry() {
  std::string* _s = _internal_mutable_entry();
  // @@protoc_insertion_point(field_mutable:corfuclient.Append.entry)
  return _s;
}
inline const std::string& Append::_internal_entry() const {
  return _impl_.entry_.Get();
}
inline void Append::_internal_set_entry(const std::string& value) {
  
  _impl_.entry_.Set(value, GetArenaForAllocation());
}
inline std::string* Append::_internal_mutable_entry() {
  
  return _impl_.entry_.Mutable(GetArenaForAllocation());
}
inline std::string* Append::release_entry() {
  // @@protoc_insertion_point(field_release:corfuclient.Append.entry)
  return _impl_.entry_.Release();
}
inline void Append::set_allocated_entry(std::string* entry) {
  if (entry != nullptr) {
    
  } else {
    
  }
  _impl_.entry_.SetAllocated(entry, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.entry_.IsDefault()) {
    _impl_.entry_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corfuclient.Append.entry)
}

// int64 currEpoch = 3;
inline void Append::clear_currepoch() {
  _impl_.currepoch_ = int64_t{0};
}
inline int64_t Append::_internal_currepoch() const {
  return _impl_.currepoch_;
}
inline int64_t Append::currepoch() const {
  // @@protoc_insertion_point(field_get:corfuclient.Append.currEpoch)
  return _internal_currepoch();
}
inline void Append::_internal_set_currepoch(int64_t value) {
  
  _impl_.currepoch_ = value;
}
inline void Append::set_currepoch(int64_t value) {
  _internal_set_currepoch(value);
  // @@protoc_insertion_point(field_set:corfuclient.Append.currEpoch)
}

// -------------------------------------------------------------------

// Read

// int64 idx = 1;
inline void Read::clear_idx() {
  _impl_.idx_ = int64_t{0};
}
inline int64_t Read::_internal_idx() const {
  return _impl_.idx_;
}
inline int64_t Read::idx() const {
  // @@protoc_insertion_point(field_get:corfuclient.Read.idx)
  return _internal_idx();
}
inline void Read::_internal_set_idx(int64_t value) {
  
  _impl_.idx_ = value;
}
inline void Read::set_idx(int64_t value) {
  _internal_set_idx(value);
  // @@protoc_insertion_point(field_set:corfuclient.Read.idx)
}

// int64 currEpoch = 2;
inline void Read::clear_currepoch() {
  _impl_.currepoch_ = int64_t{0};
}
inline int64_t Read::_internal_currepoch() const {
  return _impl_.currepoch_;
}
inline int64_t Read::currepoch() const {
  // @@protoc_insertion_point(field_get:corfuclient.Read.currEpoch)
  return _internal_currepoch();
}
inline void Read::_internal_set_currepoch(int64_t value) {
  
  _impl_.currepoch_ = value;
}
inline void Read::set_currepoch(int64_t value) {
  _internal_set_currepoch(value);
  // @@protoc_insertion_point(field_set:corfuclient.Read.currEpoch)
}

// -------------------------------------------------------------------

// Trim

// int64 idx = 1;
inline void Trim::clear_idx() {
  _impl_.idx_ = int64_t{0};
}
inline int64_t Trim::_internal_idx() const {
  return _impl_.idx_;
}
inline int64_t Trim::idx() const {
  // @@protoc_insertion_point(field_get:corfuclient.Trim.idx)
  return _internal_idx();
}
inline void Trim::_internal_set_idx(int64_t value) {
  
  _impl_.idx_ = value;
}
inline void Trim::set_idx(int64_t value) {
  _internal_set_idx(value);
  // @@protoc_insertion_point(field_set:corfuclient.Trim.idx)
}

// -------------------------------------------------------------------

// Seal

// int64 currEpoch = 1;
inline void Seal::clear_currepoch() {
  _impl_.currepoch_ = int64_t{0};
}
inline int64_t Seal::_internal_currepoch() const {
  return _impl_.currepoch_;
}
inline int64_t Seal::currepoch() const {
  // @@protoc_insertion_point(field_get:corfuclient.Seal.currEpoch)
  return _internal_currepoch();
}
inline void Seal::_internal_set_currepoch(int64_t value) {
  
  _impl_.currepoch_ = value;
}
inline void Seal::set_currepoch(int64_t value) {
  _internal_set_currepoch(value);
  // @@protoc_insertion_point(field_set:corfuclient.Seal.currEpoch)
}

// -------------------------------------------------------------------

// GetToken

// bool reqToken = 1;
inline void GetToken::clear_reqtoken() {
  _impl_.reqtoken_ = false;
}
inline bool GetToken::_internal_reqtoken() const {
  return _impl_.reqtoken_;
}
inline bool GetToken::reqtoken() const {
  // @@protoc_insertion_point(field_get:corfuclient.GetToken.reqToken)
  return _internal_reqtoken();
}
inline void GetToken::_internal_set_reqtoken(bool value) {
  
  _impl_.reqtoken_ = value;
}
inline void GetToken::set_reqtoken(bool value) {
  _internal_set_reqtoken(value);
  // @@protoc_insertion_point(field_set:corfuclient.GetToken.reqToken)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace corfuclient

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_corfuclient_2eproto
