// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: code/proto/corfuclient.proto

#include "code/proto/corfuclient.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace corfuclient {
PROTOBUF_CONSTEXPR Payload::Payload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.append_)*/nullptr
  , /*decltype(_impl_.read_)*/nullptr
  , /*decltype(_impl_.trim_)*/nullptr
  , /*decltype(_impl_.token_req_)*/nullptr
  , /*decltype(_impl_.seal_)*/nullptr
  , /*decltype(_impl_.packet_type_)*/int64_t{0}
  , /*decltype(_impl_.clientid_)*/int64_t{0}} {}
struct PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadDefaultTypeInternal() {}
  union {
    Payload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadDefaultTypeInternal _Payload_default_instance_;
PROTOBUF_CONSTEXPR Append::Append(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entry_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.idx_)*/int64_t{0}
  , /*decltype(_impl_.currepoch_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AppendDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppendDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppendDefaultTypeInternal() {}
  union {
    Append _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppendDefaultTypeInternal _Append_default_instance_;
PROTOBUF_CONSTEXPR Read::Read(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.idx_)*/int64_t{0}
  , /*decltype(_impl_.currepoch_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadDefaultTypeInternal() {}
  union {
    Read _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadDefaultTypeInternal _Read_default_instance_;
PROTOBUF_CONSTEXPR Trim::Trim(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.idx_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrimDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrimDefaultTypeInternal() {}
  union {
    Trim _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrimDefaultTypeInternal _Trim_default_instance_;
PROTOBUF_CONSTEXPR Seal::Seal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.currepoch_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SealDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SealDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SealDefaultTypeInternal() {}
  union {
    Seal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SealDefaultTypeInternal _Seal_default_instance_;
PROTOBUF_CONSTEXPR GetToken::GetToken(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.reqtoken_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetTokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetTokenDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetTokenDefaultTypeInternal() {}
  union {
    GetToken _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetTokenDefaultTypeInternal _GetToken_default_instance_;
}  // namespace corfuclient
static ::_pb::Metadata file_level_metadata_code_2fproto_2fcorfuclient_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_code_2fproto_2fcorfuclient_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_code_2fproto_2fcorfuclient_2eproto = nullptr;

const uint32_t TableStruct_code_2fproto_2fcorfuclient_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.packet_type_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.append_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.read_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.trim_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.token_req_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.clientid_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Payload, _impl_.seal_),
  ~0u,
  0,
  1,
  2,
  3,
  ~0u,
  4,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Append, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Append, _impl_.idx_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Append, _impl_.entry_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Append, _impl_.currepoch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Read, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Read, _impl_.idx_),
  PROTOBUF_FIELD_OFFSET(::corfuclient::Read, _impl_.currepoch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Trim, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Trim, _impl_.idx_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Seal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::Seal, _impl_.currepoch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfuclient::GetToken, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfuclient::GetToken, _impl_.reqtoken_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, -1, sizeof(::corfuclient::Payload)},
  { 20, -1, -1, sizeof(::corfuclient::Append)},
  { 29, -1, -1, sizeof(::corfuclient::Read)},
  { 37, -1, -1, sizeof(::corfuclient::Trim)},
  { 44, -1, -1, sizeof(::corfuclient::Seal)},
  { 51, -1, -1, sizeof(::corfuclient::GetToken)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::corfuclient::_Payload_default_instance_._instance,
  &::corfuclient::_Append_default_instance_._instance,
  &::corfuclient::_Read_default_instance_._instance,
  &::corfuclient::_Trim_default_instance_._instance,
  &::corfuclient::_Seal_default_instance_._instance,
  &::corfuclient::_GetToken_default_instance_._instance,
};

const char descriptor_table_protodef_code_2fproto_2fcorfuclient_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034code/proto/corfuclient.proto\022\013corfucli"
  "ent\"\257\002\n\007Payload\022\023\n\013packet_type\030\001 \001(\003\022(\n\006"
  "append\030\002 \001(\0132\023.corfuclient.AppendH\000\210\001\001\022$"
  "\n\004read\030\003 \001(\0132\021.corfuclient.ReadH\001\210\001\001\022$\n\004"
  "trim\030\004 \001(\0132\021.corfuclient.TrimH\002\210\001\001\022-\n\tto"
  "ken_req\030\005 \001(\0132\025.corfuclient.GetTokenH\003\210\001"
  "\001\022\020\n\010clientID\030\006 \001(\003\022$\n\004seal\030\007 \001(\0132\021.corf"
  "uclient.SealH\004\210\001\001B\t\n\007_appendB\007\n\005_readB\007\n"
  "\005_trimB\014\n\n_token_reqB\007\n\005_seal\"7\n\006Append\022"
  "\013\n\003idx\030\001 \001(\003\022\r\n\005entry\030\002 \001(\t\022\021\n\tcurrEpoch"
  "\030\003 \001(\003\"&\n\004Read\022\013\n\003idx\030\001 \001(\003\022\021\n\tcurrEpoch"
  "\030\002 \001(\003\"\023\n\004Trim\022\013\n\003idx\030\001 \001(\003\"\031\n\004Seal\022\021\n\tc"
  "urrEpoch\030\001 \001(\003\"\034\n\010GetToken\022\020\n\010reqToken\030\001"
  " \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_code_2fproto_2fcorfuclient_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_code_2fproto_2fcorfuclient_2eproto = {
    false, false, 532, descriptor_table_protodef_code_2fproto_2fcorfuclient_2eproto,
    "code/proto/corfuclient.proto",
    &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_code_2fproto_2fcorfuclient_2eproto::offsets,
    file_level_metadata_code_2fproto_2fcorfuclient_2eproto, file_level_enum_descriptors_code_2fproto_2fcorfuclient_2eproto,
    file_level_service_descriptors_code_2fproto_2fcorfuclient_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter() {
  return &descriptor_table_code_2fproto_2fcorfuclient_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_code_2fproto_2fcorfuclient_2eproto(&descriptor_table_code_2fproto_2fcorfuclient_2eproto);
namespace corfuclient {

// ===================================================================

class Payload::_Internal {
 public:
  using HasBits = decltype(std::declval<Payload>()._impl_._has_bits_);
  static const ::corfuclient::Append& append(const Payload* msg);
  static void set_has_append(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::corfuclient::Read& read(const Payload* msg);
  static void set_has_read(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::corfuclient::Trim& trim(const Payload* msg);
  static void set_has_trim(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::corfuclient::GetToken& token_req(const Payload* msg);
  static void set_has_token_req(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::corfuclient::Seal& seal(const Payload* msg);
  static void set_has_seal(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

const ::corfuclient::Append&
Payload::_Internal::append(const Payload* msg) {
  return *msg->_impl_.append_;
}
const ::corfuclient::Read&
Payload::_Internal::read(const Payload* msg) {
  return *msg->_impl_.read_;
}
const ::corfuclient::Trim&
Payload::_Internal::trim(const Payload* msg) {
  return *msg->_impl_.trim_;
}
const ::corfuclient::GetToken&
Payload::_Internal::token_req(const Payload* msg) {
  return *msg->_impl_.token_req_;
}
const ::corfuclient::Seal&
Payload::_Internal::seal(const Payload* msg) {
  return *msg->_impl_.seal_;
}
Payload::Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.Payload)
}
Payload::Payload(const Payload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Payload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.append_){nullptr}
    , decltype(_impl_.read_){nullptr}
    , decltype(_impl_.trim_){nullptr}
    , decltype(_impl_.token_req_){nullptr}
    , decltype(_impl_.seal_){nullptr}
    , decltype(_impl_.packet_type_){}
    , decltype(_impl_.clientid_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_append()) {
    _this->_impl_.append_ = new ::corfuclient::Append(*from._impl_.append_);
  }
  if (from._internal_has_read()) {
    _this->_impl_.read_ = new ::corfuclient::Read(*from._impl_.read_);
  }
  if (from._internal_has_trim()) {
    _this->_impl_.trim_ = new ::corfuclient::Trim(*from._impl_.trim_);
  }
  if (from._internal_has_token_req()) {
    _this->_impl_.token_req_ = new ::corfuclient::GetToken(*from._impl_.token_req_);
  }
  if (from._internal_has_seal()) {
    _this->_impl_.seal_ = new ::corfuclient::Seal(*from._impl_.seal_);
  }
  ::memcpy(&_impl_.packet_type_, &from._impl_.packet_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.clientid_) -
    reinterpret_cast<char*>(&_impl_.packet_type_)) + sizeof(_impl_.clientid_));
  // @@protoc_insertion_point(copy_constructor:corfuclient.Payload)
}

inline void Payload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.append_){nullptr}
    , decltype(_impl_.read_){nullptr}
    , decltype(_impl_.trim_){nullptr}
    , decltype(_impl_.token_req_){nullptr}
    , decltype(_impl_.seal_){nullptr}
    , decltype(_impl_.packet_type_){int64_t{0}}
    , decltype(_impl_.clientid_){int64_t{0}}
  };
}

Payload::~Payload() {
  // @@protoc_insertion_point(destructor:corfuclient.Payload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Payload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.append_;
  if (this != internal_default_instance()) delete _impl_.read_;
  if (this != internal_default_instance()) delete _impl_.trim_;
  if (this != internal_default_instance()) delete _impl_.token_req_;
  if (this != internal_default_instance()) delete _impl_.seal_;
}

void Payload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.Payload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(_impl_.append_ != nullptr);
      _impl_.append_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.read_ != nullptr);
      _impl_.read_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.trim_ != nullptr);
      _impl_.trim_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(_impl_.token_req_ != nullptr);
      _impl_.token_req_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(_impl_.seal_ != nullptr);
      _impl_.seal_->Clear();
    }
  }
  ::memset(&_impl_.packet_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.clientid_) -
      reinterpret_cast<char*>(&_impl_.packet_type_)) + sizeof(_impl_.clientid_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Payload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 packet_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.packet_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfuclient.Append append = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_append(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfuclient.Read read = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_read(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfuclient.Trim trim = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_trim(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfuclient.GetToken token_req = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_token_req(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 clientID = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfuclient.Seal seal = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_seal(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Payload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.Payload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_packet_type(), target);
  }

  // optional .corfuclient.Append append = 2;
  if (_internal_has_append()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::append(this),
        _Internal::append(this).GetCachedSize(), target, stream);
  }

  // optional .corfuclient.Read read = 3;
  if (_internal_has_read()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::read(this),
        _Internal::read(this).GetCachedSize(), target, stream);
  }

  // optional .corfuclient.Trim trim = 4;
  if (_internal_has_trim()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::trim(this),
        _Internal::trim(this).GetCachedSize(), target, stream);
  }

  // optional .corfuclient.GetToken token_req = 5;
  if (_internal_has_token_req()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::token_req(this),
        _Internal::token_req(this).GetCachedSize(), target, stream);
  }

  // int64 clientID = 6;
  if (this->_internal_clientid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_clientid(), target);
  }

  // optional .corfuclient.Seal seal = 7;
  if (_internal_has_seal()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::seal(this),
        _Internal::seal(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.Payload)
  return target;
}

size_t Payload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.Payload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional .corfuclient.Append append = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.append_);
    }

    // optional .corfuclient.Read read = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.read_);
    }

    // optional .corfuclient.Trim trim = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.trim_);
    }

    // optional .corfuclient.GetToken token_req = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.token_req_);
    }

    // optional .corfuclient.Seal seal = 7;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.seal_);
    }

  }
  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_packet_type());
  }

  // int64 clientID = 6;
  if (this->_internal_clientid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_clientid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Payload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Payload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Payload::GetClassData() const { return &_class_data_; }


void Payload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Payload*>(&to_msg);
  auto& from = static_cast<const Payload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.Payload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_append()->::corfuclient::Append::MergeFrom(
          from._internal_append());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_read()->::corfuclient::Read::MergeFrom(
          from._internal_read());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_trim()->::corfuclient::Trim::MergeFrom(
          from._internal_trim());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_token_req()->::corfuclient::GetToken::MergeFrom(
          from._internal_token_req());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_mutable_seal()->::corfuclient::Seal::MergeFrom(
          from._internal_seal());
    }
  }
  if (from._internal_packet_type() != 0) {
    _this->_internal_set_packet_type(from._internal_packet_type());
  }
  if (from._internal_clientid() != 0) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Payload::CopyFrom(const Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Payload::IsInitialized() const {
  return true;
}

void Payload::InternalSwap(Payload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Payload, _impl_.clientid_)
      + sizeof(Payload::_impl_.clientid_)
      - PROTOBUF_FIELD_OFFSET(Payload, _impl_.append_)>(
          reinterpret_cast<char*>(&_impl_.append_),
          reinterpret_cast<char*>(&other->_impl_.append_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Payload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[0]);
}

// ===================================================================

class Append::_Internal {
 public:
};

Append::Append(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.Append)
}
Append::Append(const Append& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Append* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entry_){}
    , decltype(_impl_.idx_){}
    , decltype(_impl_.currepoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.entry_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.entry_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_entry().empty()) {
    _this->_impl_.entry_.Set(from._internal_entry(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.idx_, &from._impl_.idx_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.currepoch_) -
    reinterpret_cast<char*>(&_impl_.idx_)) + sizeof(_impl_.currepoch_));
  // @@protoc_insertion_point(copy_constructor:corfuclient.Append)
}

inline void Append::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entry_){}
    , decltype(_impl_.idx_){int64_t{0}}
    , decltype(_impl_.currepoch_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.entry_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.entry_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Append::~Append() {
  // @@protoc_insertion_point(destructor:corfuclient.Append)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Append::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entry_.Destroy();
}

void Append::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Append::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.Append)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entry_.ClearToEmpty();
  ::memset(&_impl_.idx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.currepoch_) -
      reinterpret_cast<char*>(&_impl_.idx_)) + sizeof(_impl_.currepoch_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Append::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 idx = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.idx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string entry = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_entry();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "corfuclient.Append.entry"));
        } else
          goto handle_unusual;
        continue;
      // int64 currEpoch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.currepoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Append::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.Append)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_idx(), target);
  }

  // string entry = 2;
  if (!this->_internal_entry().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_entry().data(), static_cast<int>(this->_internal_entry().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "corfuclient.Append.entry");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_entry(), target);
  }

  // int64 currEpoch = 3;
  if (this->_internal_currepoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_currepoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.Append)
  return target;
}

size_t Append::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.Append)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string entry = 2;
  if (!this->_internal_entry().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_entry());
  }

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_idx());
  }

  // int64 currEpoch = 3;
  if (this->_internal_currepoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_currepoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Append::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Append::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Append::GetClassData() const { return &_class_data_; }


void Append::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Append*>(&to_msg);
  auto& from = static_cast<const Append&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.Append)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_entry().empty()) {
    _this->_internal_set_entry(from._internal_entry());
  }
  if (from._internal_idx() != 0) {
    _this->_internal_set_idx(from._internal_idx());
  }
  if (from._internal_currepoch() != 0) {
    _this->_internal_set_currepoch(from._internal_currepoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Append::CopyFrom(const Append& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.Append)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Append::IsInitialized() const {
  return true;
}

void Append::InternalSwap(Append* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.entry_, lhs_arena,
      &other->_impl_.entry_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Append, _impl_.currepoch_)
      + sizeof(Append::_impl_.currepoch_)
      - PROTOBUF_FIELD_OFFSET(Append, _impl_.idx_)>(
          reinterpret_cast<char*>(&_impl_.idx_),
          reinterpret_cast<char*>(&other->_impl_.idx_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Append::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[1]);
}

// ===================================================================

class Read::_Internal {
 public:
};

Read::Read(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.Read)
}
Read::Read(const Read& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Read* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.idx_){}
    , decltype(_impl_.currepoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.idx_, &from._impl_.idx_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.currepoch_) -
    reinterpret_cast<char*>(&_impl_.idx_)) + sizeof(_impl_.currepoch_));
  // @@protoc_insertion_point(copy_constructor:corfuclient.Read)
}

inline void Read::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.idx_){int64_t{0}}
    , decltype(_impl_.currepoch_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Read::~Read() {
  // @@protoc_insertion_point(destructor:corfuclient.Read)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Read::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Read::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Read::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.Read)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.idx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.currepoch_) -
      reinterpret_cast<char*>(&_impl_.idx_)) + sizeof(_impl_.currepoch_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Read::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 idx = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.idx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 currEpoch = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.currepoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Read::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.Read)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_idx(), target);
  }

  // int64 currEpoch = 2;
  if (this->_internal_currepoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_currepoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.Read)
  return target;
}

size_t Read::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.Read)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_idx());
  }

  // int64 currEpoch = 2;
  if (this->_internal_currepoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_currepoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Read::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Read::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Read::GetClassData() const { return &_class_data_; }


void Read::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Read*>(&to_msg);
  auto& from = static_cast<const Read&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.Read)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_idx() != 0) {
    _this->_internal_set_idx(from._internal_idx());
  }
  if (from._internal_currepoch() != 0) {
    _this->_internal_set_currepoch(from._internal_currepoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Read::CopyFrom(const Read& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.Read)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Read::IsInitialized() const {
  return true;
}

void Read::InternalSwap(Read* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Read, _impl_.currepoch_)
      + sizeof(Read::_impl_.currepoch_)
      - PROTOBUF_FIELD_OFFSET(Read, _impl_.idx_)>(
          reinterpret_cast<char*>(&_impl_.idx_),
          reinterpret_cast<char*>(&other->_impl_.idx_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Read::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[2]);
}

// ===================================================================

class Trim::_Internal {
 public:
};

Trim::Trim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.Trim)
}
Trim::Trim(const Trim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Trim* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.idx_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.idx_ = from._impl_.idx_;
  // @@protoc_insertion_point(copy_constructor:corfuclient.Trim)
}

inline void Trim::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.idx_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Trim::~Trim() {
  // @@protoc_insertion_point(destructor:corfuclient.Trim)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Trim::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Trim::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Trim::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.Trim)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.idx_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Trim::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 idx = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.idx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Trim::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.Trim)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_idx(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.Trim)
  return target;
}

size_t Trim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.Trim)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 idx = 1;
  if (this->_internal_idx() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_idx());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Trim::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Trim::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Trim::GetClassData() const { return &_class_data_; }


void Trim::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Trim*>(&to_msg);
  auto& from = static_cast<const Trim&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.Trim)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_idx() != 0) {
    _this->_internal_set_idx(from._internal_idx());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Trim::CopyFrom(const Trim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.Trim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Trim::IsInitialized() const {
  return true;
}

void Trim::InternalSwap(Trim* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.idx_, other->_impl_.idx_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Trim::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[3]);
}

// ===================================================================

class Seal::_Internal {
 public:
};

Seal::Seal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.Seal)
}
Seal::Seal(const Seal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Seal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.currepoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.currepoch_ = from._impl_.currepoch_;
  // @@protoc_insertion_point(copy_constructor:corfuclient.Seal)
}

inline void Seal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.currepoch_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Seal::~Seal() {
  // @@protoc_insertion_point(destructor:corfuclient.Seal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Seal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Seal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Seal::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.Seal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.currepoch_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Seal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 currEpoch = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.currepoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Seal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.Seal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 currEpoch = 1;
  if (this->_internal_currepoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_currepoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.Seal)
  return target;
}

size_t Seal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.Seal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 currEpoch = 1;
  if (this->_internal_currepoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_currepoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Seal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Seal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Seal::GetClassData() const { return &_class_data_; }


void Seal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Seal*>(&to_msg);
  auto& from = static_cast<const Seal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.Seal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_currepoch() != 0) {
    _this->_internal_set_currepoch(from._internal_currepoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Seal::CopyFrom(const Seal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.Seal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Seal::IsInitialized() const {
  return true;
}

void Seal::InternalSwap(Seal* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.currepoch_, other->_impl_.currepoch_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Seal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[4]);
}

// ===================================================================

class GetToken::_Internal {
 public:
};

GetToken::GetToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfuclient.GetToken)
}
GetToken::GetToken(const GetToken& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetToken* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.reqtoken_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.reqtoken_ = from._impl_.reqtoken_;
  // @@protoc_insertion_point(copy_constructor:corfuclient.GetToken)
}

inline void GetToken::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.reqtoken_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetToken::~GetToken() {
  // @@protoc_insertion_point(destructor:corfuclient.GetToken)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetToken::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetToken::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetToken::Clear() {
// @@protoc_insertion_point(message_clear_start:corfuclient.GetToken)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqtoken_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetToken::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool reqToken = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.reqtoken_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetToken::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfuclient.GetToken)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool reqToken = 1;
  if (this->_internal_reqtoken() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_reqtoken(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfuclient.GetToken)
  return target;
}

size_t GetToken::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfuclient.GetToken)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool reqToken = 1;
  if (this->_internal_reqtoken() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetToken::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetToken::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetToken::GetClassData() const { return &_class_data_; }


void GetToken::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetToken*>(&to_msg);
  auto& from = static_cast<const GetToken&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfuclient.GetToken)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_reqtoken() != 0) {
    _this->_internal_set_reqtoken(from._internal_reqtoken());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetToken::CopyFrom(const GetToken& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfuclient.GetToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetToken::IsInitialized() const {
  return true;
}

void GetToken::InternalSwap(GetToken* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.reqtoken_, other->_impl_.reqtoken_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetToken::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_code_2fproto_2fcorfuclient_2eproto_getter, &descriptor_table_code_2fproto_2fcorfuclient_2eproto_once,
      file_level_metadata_code_2fproto_2fcorfuclient_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace corfuclient
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::corfuclient::Payload*
Arena::CreateMaybeMessage< ::corfuclient::Payload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::Payload >(arena);
}
template<> PROTOBUF_NOINLINE ::corfuclient::Append*
Arena::CreateMaybeMessage< ::corfuclient::Append >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::Append >(arena);
}
template<> PROTOBUF_NOINLINE ::corfuclient::Read*
Arena::CreateMaybeMessage< ::corfuclient::Read >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::Read >(arena);
}
template<> PROTOBUF_NOINLINE ::corfuclient::Trim*
Arena::CreateMaybeMessage< ::corfuclient::Trim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::Trim >(arena);
}
template<> PROTOBUF_NOINLINE ::corfuclient::Seal*
Arena::CreateMaybeMessage< ::corfuclient::Seal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::Seal >(arena);
}
template<> PROTOBUF_NOINLINE ::corfuclient::GetToken*
Arena::CreateMaybeMessage< ::corfuclient::GetToken >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfuclient::GetToken >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
