// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corfusequencer.proto

#include "corfusequencer.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace corfusequencer {
PROTOBUF_CONSTEXPR Payload::Payload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.send_token_)*/nullptr
  , /*decltype(_impl_.packet_type_)*/int64_t{0}} {}
struct PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadDefaultTypeInternal() {}
  union {
    Payload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadDefaultTypeInternal _Payload_default_instance_;
PROTOBUF_CONSTEXPR SendToken::SendToken(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.token_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendTokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendTokenDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendTokenDefaultTypeInternal() {}
  union {
    SendToken _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendTokenDefaultTypeInternal _SendToken_default_instance_;
}  // namespace corfusequencer
static ::_pb::Metadata file_level_metadata_corfusequencer_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_corfusequencer_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_corfusequencer_2eproto = nullptr;

const uint32_t TableStruct_corfusequencer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::corfusequencer::Payload, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::corfusequencer::Payload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfusequencer::Payload, _impl_.packet_type_),
  PROTOBUF_FIELD_OFFSET(::corfusequencer::Payload, _impl_.send_token_),
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::corfusequencer::SendToken, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::corfusequencer::SendToken, _impl_.token_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::corfusequencer::Payload)},
  { 10, -1, -1, sizeof(::corfusequencer::SendToken)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::corfusequencer::_Payload_default_instance_._instance,
  &::corfusequencer::_SendToken_default_instance_._instance,
};

const char descriptor_table_protodef_corfusequencer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024corfusequencer.proto\022\016corfusequencer\"a"
  "\n\007Payload\022\023\n\013packet_type\030\001 \001(\003\0222\n\nsend_t"
  "oken\030\002 \001(\0132\031.corfusequencer.SendTokenH\000\210"
  "\001\001B\r\n\013_send_token\"\032\n\tSendToken\022\r\n\005token\030"
  "\001 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_corfusequencer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_corfusequencer_2eproto = {
    false, false, 173, descriptor_table_protodef_corfusequencer_2eproto,
    "corfusequencer.proto",
    &descriptor_table_corfusequencer_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_corfusequencer_2eproto::offsets,
    file_level_metadata_corfusequencer_2eproto, file_level_enum_descriptors_corfusequencer_2eproto,
    file_level_service_descriptors_corfusequencer_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_corfusequencer_2eproto_getter() {
  return &descriptor_table_corfusequencer_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_corfusequencer_2eproto(&descriptor_table_corfusequencer_2eproto);
namespace corfusequencer {

// ===================================================================

class Payload::_Internal {
 public:
  using HasBits = decltype(std::declval<Payload>()._impl_._has_bits_);
  static const ::corfusequencer::SendToken& send_token(const Payload* msg);
  static void set_has_send_token(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::corfusequencer::SendToken&
Payload::_Internal::send_token(const Payload* msg) {
  return *msg->_impl_.send_token_;
}
Payload::Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfusequencer.Payload)
}
Payload::Payload(const Payload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Payload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.send_token_){nullptr}
    , decltype(_impl_.packet_type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_send_token()) {
    _this->_impl_.send_token_ = new ::corfusequencer::SendToken(*from._impl_.send_token_);
  }
  _this->_impl_.packet_type_ = from._impl_.packet_type_;
  // @@protoc_insertion_point(copy_constructor:corfusequencer.Payload)
}

inline void Payload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.send_token_){nullptr}
    , decltype(_impl_.packet_type_){int64_t{0}}
  };
}

Payload::~Payload() {
  // @@protoc_insertion_point(destructor:corfusequencer.Payload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Payload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.send_token_;
}

void Payload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:corfusequencer.Payload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.send_token_ != nullptr);
    _impl_.send_token_->Clear();
  }
  _impl_.packet_type_ = int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Payload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 packet_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.packet_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .corfusequencer.SendToken send_token = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Payload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfusequencer.Payload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_packet_type(), target);
  }

  // optional .corfusequencer.SendToken send_token = 2;
  if (_internal_has_send_token()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::send_token(this),
        _Internal::send_token(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfusequencer.Payload)
  return target;
}

size_t Payload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfusequencer.Payload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .corfusequencer.SendToken send_token = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.send_token_);
  }

  // int64 packet_type = 1;
  if (this->_internal_packet_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_packet_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Payload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Payload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Payload::GetClassData() const { return &_class_data_; }


void Payload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Payload*>(&to_msg);
  auto& from = static_cast<const Payload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfusequencer.Payload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_send_token()) {
    _this->_internal_mutable_send_token()->::corfusequencer::SendToken::MergeFrom(
        from._internal_send_token());
  }
  if (from._internal_packet_type() != 0) {
    _this->_internal_set_packet_type(from._internal_packet_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Payload::CopyFrom(const Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfusequencer.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Payload::IsInitialized() const {
  return true;
}

void Payload::InternalSwap(Payload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Payload, _impl_.packet_type_)
      + sizeof(Payload::_impl_.packet_type_)
      - PROTOBUF_FIELD_OFFSET(Payload, _impl_.send_token_)>(
          reinterpret_cast<char*>(&_impl_.send_token_),
          reinterpret_cast<char*>(&other->_impl_.send_token_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Payload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfusequencer_2eproto_getter, &descriptor_table_corfusequencer_2eproto_once,
      file_level_metadata_corfusequencer_2eproto[0]);
}

// ===================================================================

class SendToken::_Internal {
 public:
};

SendToken::SendToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:corfusequencer.SendToken)
}
SendToken::SendToken(const SendToken& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendToken* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.token_ = from._impl_.token_;
  // @@protoc_insertion_point(copy_constructor:corfusequencer.SendToken)
}

inline void SendToken::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SendToken::~SendToken() {
  // @@protoc_insertion_point(destructor:corfusequencer.SendToken)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendToken::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SendToken::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendToken::Clear() {
// @@protoc_insertion_point(message_clear_start:corfusequencer.SendToken)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendToken::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.token_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendToken::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:corfusequencer.SendToken)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 token = 1;
  if (this->_internal_token() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_token(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corfusequencer.SendToken)
  return target;
}

size_t SendToken::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:corfusequencer.SendToken)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 token = 1;
  if (this->_internal_token() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendToken::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendToken::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendToken::GetClassData() const { return &_class_data_; }


void SendToken::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendToken*>(&to_msg);
  auto& from = static_cast<const SendToken&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:corfusequencer.SendToken)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_token() != 0) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendToken::CopyFrom(const SendToken& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:corfusequencer.SendToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendToken::IsInitialized() const {
  return true;
}

void SendToken::InternalSwap(SendToken* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.token_, other->_impl_.token_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendToken::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_corfusequencer_2eproto_getter, &descriptor_table_corfusequencer_2eproto_once,
      file_level_metadata_corfusequencer_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace corfusequencer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::corfusequencer::Payload*
Arena::CreateMaybeMessage< ::corfusequencer::Payload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfusequencer::Payload >(arena);
}
template<> PROTOBUF_NOINLINE ::corfusequencer::SendToken*
Arena::CreateMaybeMessage< ::corfusequencer::SendToken >(Arena* arena) {
  return Arena::CreateMessageInternal< ::corfusequencer::SendToken >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
