install_headers('base_client.h')
#install_headers('base_sequencer.h')
install_headers('base_storage.h')
install_headers('pringles_client.h')
install_headers('pringles_storage.h')
#install_headers('simple_client.h')
install_headers('utils.h')
install_headers('ring_headers.h')
install_headers('network.h')
install_headers('trace.h')
install_headers('measure.h')
