// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/corfusequencer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfusequencer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfusequencer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fcorfusequencer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fcorfusequencer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcorfusequencer_2eproto;
namespace corfusequencer {
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class SendToken;
struct SendTokenDefaultTypeInternal;
extern SendTokenDefaultTypeInternal _SendToken_default_instance_;
}  // namespace corfusequencer
PROTOBUF_NAMESPACE_OPEN
template<> ::corfusequencer::Payload* Arena::CreateMaybeMessage<::corfusequencer::Payload>(Arena*);
template<> ::corfusequencer::SendToken* Arena::CreateMaybeMessage<::corfusequencer::SendToken>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace corfusequencer {

// ===================================================================

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfusequencer.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Payload& from) {
    Payload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfusequencer.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSendTokenFieldNumber = 2,
    kPacketTypeFieldNumber = 1,
  };
  // optional .corfusequencer.SendToken send_token = 2;
  bool has_send_token() const;
  private:
  bool _internal_has_send_token() const;
  public:
  void clear_send_token();
  const ::corfusequencer::SendToken& send_token() const;
  PROTOBUF_NODISCARD ::corfusequencer::SendToken* release_send_token();
  ::corfusequencer::SendToken* mutable_send_token();
  void set_allocated_send_token(::corfusequencer::SendToken* send_token);
  private:
  const ::corfusequencer::SendToken& _internal_send_token() const;
  ::corfusequencer::SendToken* _internal_mutable_send_token();
  public:
  void unsafe_arena_set_allocated_send_token(
      ::corfusequencer::SendToken* send_token);
  ::corfusequencer::SendToken* unsafe_arena_release_send_token();

  // int64 packet_type = 1;
  void clear_packet_type();
  int64_t packet_type() const;
  void set_packet_type(int64_t value);
  private:
  int64_t _internal_packet_type() const;
  void _internal_set_packet_type(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfusequencer.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::corfusequencer::SendToken* send_token_;
    int64_t packet_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfusequencer_2eproto;
};
// -------------------------------------------------------------------

class SendToken final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfusequencer.SendToken) */ {
 public:
  inline SendToken() : SendToken(nullptr) {}
  ~SendToken() override;
  explicit PROTOBUF_CONSTEXPR SendToken(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendToken(const SendToken& from);
  SendToken(SendToken&& from) noexcept
    : SendToken() {
    *this = ::std::move(from);
  }

  inline SendToken& operator=(const SendToken& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendToken& operator=(SendToken&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendToken& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendToken* internal_default_instance() {
    return reinterpret_cast<const SendToken*>(
               &_SendToken_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendToken& a, SendToken& b) {
    a.Swap(&b);
  }
  inline void Swap(SendToken* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendToken* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendToken* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendToken>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendToken& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendToken& from) {
    SendToken::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendToken* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfusequencer.SendToken";
  }
  protected:
  explicit SendToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
  };
  // int64 token = 1;
  void clear_token();
  int64_t token() const;
  void set_token(int64_t value);
  private:
  int64_t _internal_token() const;
  void _internal_set_token(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfusequencer.SendToken)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t token_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfusequencer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Payload

// int64 packet_type = 1;
inline void Payload::clear_packet_type() {
  _impl_.packet_type_ = int64_t{0};
}
inline int64_t Payload::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline int64_t Payload::packet_type() const {
  // @@protoc_insertion_point(field_get:corfusequencer.Payload.packet_type)
  return _internal_packet_type();
}
inline void Payload::_internal_set_packet_type(int64_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Payload::set_packet_type(int64_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:corfusequencer.Payload.packet_type)
}

// optional .corfusequencer.SendToken send_token = 2;
inline bool Payload::_internal_has_send_token() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.send_token_ != nullptr);
  return value;
}
inline bool Payload::has_send_token() const {
  return _internal_has_send_token();
}
inline void Payload::clear_send_token() {
  if (_impl_.send_token_ != nullptr) _impl_.send_token_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::corfusequencer::SendToken& Payload::_internal_send_token() const {
  const ::corfusequencer::SendToken* p = _impl_.send_token_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfusequencer::SendToken&>(
      ::corfusequencer::_SendToken_default_instance_);
}
inline const ::corfusequencer::SendToken& Payload::send_token() const {
  // @@protoc_insertion_point(field_get:corfusequencer.Payload.send_token)
  return _internal_send_token();
}
inline void Payload::unsafe_arena_set_allocated_send_token(
    ::corfusequencer::SendToken* send_token) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.send_token_);
  }
  _impl_.send_token_ = send_token;
  if (send_token) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfusequencer.Payload.send_token)
}
inline ::corfusequencer::SendToken* Payload::release_send_token() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfusequencer::SendToken* temp = _impl_.send_token_;
  _impl_.send_token_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfusequencer::SendToken* Payload::unsafe_arena_release_send_token() {
  // @@protoc_insertion_point(field_release:corfusequencer.Payload.send_token)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfusequencer::SendToken* temp = _impl_.send_token_;
  _impl_.send_token_ = nullptr;
  return temp;
}
inline ::corfusequencer::SendToken* Payload::_internal_mutable_send_token() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.send_token_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfusequencer::SendToken>(GetArenaForAllocation());
    _impl_.send_token_ = p;
  }
  return _impl_.send_token_;
}
inline ::corfusequencer::SendToken* Payload::mutable_send_token() {
  ::corfusequencer::SendToken* _msg = _internal_mutable_send_token();
  // @@protoc_insertion_point(field_mutable:corfusequencer.Payload.send_token)
  return _msg;
}
inline void Payload::set_allocated_send_token(::corfusequencer::SendToken* send_token) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.send_token_;
  }
  if (send_token) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(send_token);
    if (message_arena != submessage_arena) {
      send_token = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_token, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.send_token_ = send_token;
  // @@protoc_insertion_point(field_set_allocated:corfusequencer.Payload.send_token)
}

// -------------------------------------------------------------------

// SendToken

// int64 token = 1;
inline void SendToken::clear_token() {
  _impl_.token_ = int64_t{0};
}
inline int64_t SendToken::_internal_token() const {
  return _impl_.token_;
}
inline int64_t SendToken::token() const {
  // @@protoc_insertion_point(field_get:corfusequencer.SendToken.token)
  return _internal_token();
}
inline void SendToken::_internal_set_token(int64_t value) {
  
  _impl_.token_ = value;
}
inline void SendToken::set_token(int64_t value) {
  _internal_set_token(value);
  // @@protoc_insertion_point(field_set:corfusequencer.SendToken.token)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace corfusequencer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfusequencer_2eproto
