// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/corfustorage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfustorage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfustorage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fcorfustorage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fcorfustorage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcorfustorage_2eproto;
namespace corfustorage {
class Ack;
struct AckDefaultTypeInternal;
extern AckDefaultTypeInternal _Ack_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class Read;
struct ReadDefaultTypeInternal;
extern ReadDefaultTypeInternal _Read_default_instance_;
class Seal;
struct SealDefaultTypeInternal;
extern SealDefaultTypeInternal _Seal_default_instance_;
class errDeleted;
struct errDeletedDefaultTypeInternal;
extern errDeletedDefaultTypeInternal _errDeleted_default_instance_;
class errSealed;
struct errSealedDefaultTypeInternal;
extern errSealedDefaultTypeInternal _errSealed_default_instance_;
class errUnwritten;
struct errUnwrittenDefaultTypeInternal;
extern errUnwrittenDefaultTypeInternal _errUnwritten_default_instance_;
class errWritten;
struct errWrittenDefaultTypeInternal;
extern errWrittenDefaultTypeInternal _errWritten_default_instance_;
}  // namespace corfustorage
PROTOBUF_NAMESPACE_OPEN
template<> ::corfustorage::Ack* Arena::CreateMaybeMessage<::corfustorage::Ack>(Arena*);
template<> ::corfustorage::Payload* Arena::CreateMaybeMessage<::corfustorage::Payload>(Arena*);
template<> ::corfustorage::Read* Arena::CreateMaybeMessage<::corfustorage::Read>(Arena*);
template<> ::corfustorage::Seal* Arena::CreateMaybeMessage<::corfustorage::Seal>(Arena*);
template<> ::corfustorage::errDeleted* Arena::CreateMaybeMessage<::corfustorage::errDeleted>(Arena*);
template<> ::corfustorage::errSealed* Arena::CreateMaybeMessage<::corfustorage::errSealed>(Arena*);
template<> ::corfustorage::errUnwritten* Arena::CreateMaybeMessage<::corfustorage::errUnwritten>(Arena*);
template<> ::corfustorage::errWritten* Arena::CreateMaybeMessage<::corfustorage::errWritten>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace corfustorage {

// ===================================================================

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Payload& from) {
    Payload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAckFieldNumber = 2,
    kErrSealedFieldNumber = 3,
    kErrUnwrittenFieldNumber = 4,
    kErrWrittenFieldNumber = 5,
    kReadFieldNumber = 6,
    kSealFieldNumber = 7,
    kErrDeletedFieldNumber = 8,
    kPacketTypeFieldNumber = 1,
  };
  // optional .corfustorage.Ack ack = 2;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;
  public:
  void clear_ack();
  const ::corfustorage::Ack& ack() const;
  PROTOBUF_NODISCARD ::corfustorage::Ack* release_ack();
  ::corfustorage::Ack* mutable_ack();
  void set_allocated_ack(::corfustorage::Ack* ack);
  private:
  const ::corfustorage::Ack& _internal_ack() const;
  ::corfustorage::Ack* _internal_mutable_ack();
  public:
  void unsafe_arena_set_allocated_ack(
      ::corfustorage::Ack* ack);
  ::corfustorage::Ack* unsafe_arena_release_ack();

  // optional .corfustorage.errSealed err_sealed = 3;
  bool has_err_sealed() const;
  private:
  bool _internal_has_err_sealed() const;
  public:
  void clear_err_sealed();
  const ::corfustorage::errSealed& err_sealed() const;
  PROTOBUF_NODISCARD ::corfustorage::errSealed* release_err_sealed();
  ::corfustorage::errSealed* mutable_err_sealed();
  void set_allocated_err_sealed(::corfustorage::errSealed* err_sealed);
  private:
  const ::corfustorage::errSealed& _internal_err_sealed() const;
  ::corfustorage::errSealed* _internal_mutable_err_sealed();
  public:
  void unsafe_arena_set_allocated_err_sealed(
      ::corfustorage::errSealed* err_sealed);
  ::corfustorage::errSealed* unsafe_arena_release_err_sealed();

  // optional .corfustorage.errUnwritten err_unwritten = 4;
  bool has_err_unwritten() const;
  private:
  bool _internal_has_err_unwritten() const;
  public:
  void clear_err_unwritten();
  const ::corfustorage::errUnwritten& err_unwritten() const;
  PROTOBUF_NODISCARD ::corfustorage::errUnwritten* release_err_unwritten();
  ::corfustorage::errUnwritten* mutable_err_unwritten();
  void set_allocated_err_unwritten(::corfustorage::errUnwritten* err_unwritten);
  private:
  const ::corfustorage::errUnwritten& _internal_err_unwritten() const;
  ::corfustorage::errUnwritten* _internal_mutable_err_unwritten();
  public:
  void unsafe_arena_set_allocated_err_unwritten(
      ::corfustorage::errUnwritten* err_unwritten);
  ::corfustorage::errUnwritten* unsafe_arena_release_err_unwritten();

  // optional .corfustorage.errWritten err_written = 5;
  bool has_err_written() const;
  private:
  bool _internal_has_err_written() const;
  public:
  void clear_err_written();
  const ::corfustorage::errWritten& err_written() const;
  PROTOBUF_NODISCARD ::corfustorage::errWritten* release_err_written();
  ::corfustorage::errWritten* mutable_err_written();
  void set_allocated_err_written(::corfustorage::errWritten* err_written);
  private:
  const ::corfustorage::errWritten& _internal_err_written() const;
  ::corfustorage::errWritten* _internal_mutable_err_written();
  public:
  void unsafe_arena_set_allocated_err_written(
      ::corfustorage::errWritten* err_written);
  ::corfustorage::errWritten* unsafe_arena_release_err_written();

  // optional .corfustorage.Read read = 6;
  bool has_read() const;
  private:
  bool _internal_has_read() const;
  public:
  void clear_read();
  const ::corfustorage::Read& read() const;
  PROTOBUF_NODISCARD ::corfustorage::Read* release_read();
  ::corfustorage::Read* mutable_read();
  void set_allocated_read(::corfustorage::Read* read);
  private:
  const ::corfustorage::Read& _internal_read() const;
  ::corfustorage::Read* _internal_mutable_read();
  public:
  void unsafe_arena_set_allocated_read(
      ::corfustorage::Read* read);
  ::corfustorage::Read* unsafe_arena_release_read();

  // optional .corfustorage.Seal seal = 7;
  bool has_seal() const;
  private:
  bool _internal_has_seal() const;
  public:
  void clear_seal();
  const ::corfustorage::Seal& seal() const;
  PROTOBUF_NODISCARD ::corfustorage::Seal* release_seal();
  ::corfustorage::Seal* mutable_seal();
  void set_allocated_seal(::corfustorage::Seal* seal);
  private:
  const ::corfustorage::Seal& _internal_seal() const;
  ::corfustorage::Seal* _internal_mutable_seal();
  public:
  void unsafe_arena_set_allocated_seal(
      ::corfustorage::Seal* seal);
  ::corfustorage::Seal* unsafe_arena_release_seal();

  // optional .corfustorage.errDeleted err_deleted = 8;
  bool has_err_deleted() const;
  private:
  bool _internal_has_err_deleted() const;
  public:
  void clear_err_deleted();
  const ::corfustorage::errDeleted& err_deleted() const;
  PROTOBUF_NODISCARD ::corfustorage::errDeleted* release_err_deleted();
  ::corfustorage::errDeleted* mutable_err_deleted();
  void set_allocated_err_deleted(::corfustorage::errDeleted* err_deleted);
  private:
  const ::corfustorage::errDeleted& _internal_err_deleted() const;
  ::corfustorage::errDeleted* _internal_mutable_err_deleted();
  public:
  void unsafe_arena_set_allocated_err_deleted(
      ::corfustorage::errDeleted* err_deleted);
  ::corfustorage::errDeleted* unsafe_arena_release_err_deleted();

  // int64 packet_type = 1;
  void clear_packet_type();
  int64_t packet_type() const;
  void set_packet_type(int64_t value);
  private:
  int64_t _internal_packet_type() const;
  void _internal_set_packet_type(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::corfustorage::Ack* ack_;
    ::corfustorage::errSealed* err_sealed_;
    ::corfustorage::errUnwritten* err_unwritten_;
    ::corfustorage::errWritten* err_written_;
    ::corfustorage::Read* read_;
    ::corfustorage::Seal* seal_;
    ::corfustorage::errDeleted* err_deleted_;
    int64_t packet_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class Ack final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.Ack) */ {
 public:
  inline Ack() : Ack(nullptr) {}
  ~Ack() override;
  explicit PROTOBUF_CONSTEXPR Ack(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ack(const Ack& from);
  Ack(Ack&& from) noexcept
    : Ack() {
    *this = ::std::move(from);
  }

  inline Ack& operator=(const Ack& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ack& operator=(Ack&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ack& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ack* internal_default_instance() {
    return reinterpret_cast<const Ack*>(
               &_Ack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Ack& a, Ack& b) {
    a.Swap(&b);
  }
  inline void Swap(Ack* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ack* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ack* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ack>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ack& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Ack& from) {
    Ack::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ack* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.Ack";
  }
  protected:
  explicit Ack(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAckCodeFieldNumber = 1,
  };
  // bool ack_code = 1;
  void clear_ack_code();
  bool ack_code() const;
  void set_ack_code(bool value);
  private:
  bool _internal_ack_code() const;
  void _internal_set_ack_code(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.Ack)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool ack_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class errSealed final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.errSealed) */ {
 public:
  inline errSealed() : errSealed(nullptr) {}
  ~errSealed() override;
  explicit PROTOBUF_CONSTEXPR errSealed(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  errSealed(const errSealed& from);
  errSealed(errSealed&& from) noexcept
    : errSealed() {
    *this = ::std::move(from);
  }

  inline errSealed& operator=(const errSealed& from) {
    CopyFrom(from);
    return *this;
  }
  inline errSealed& operator=(errSealed&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const errSealed& default_instance() {
    return *internal_default_instance();
  }
  static inline const errSealed* internal_default_instance() {
    return reinterpret_cast<const errSealed*>(
               &_errSealed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(errSealed& a, errSealed& b) {
    a.Swap(&b);
  }
  inline void Swap(errSealed* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(errSealed* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  errSealed* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<errSealed>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const errSealed& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const errSealed& from) {
    errSealed::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(errSealed* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.errSealed";
  }
  protected:
  explicit errSealed(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrCodeFieldNumber = 1,
  };
  // bool err_code = 1;
  void clear_err_code();
  bool err_code() const;
  void set_err_code(bool value);
  private:
  bool _internal_err_code() const;
  void _internal_set_err_code(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.errSealed)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool err_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class errUnwritten final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.errUnwritten) */ {
 public:
  inline errUnwritten() : errUnwritten(nullptr) {}
  ~errUnwritten() override;
  explicit PROTOBUF_CONSTEXPR errUnwritten(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  errUnwritten(const errUnwritten& from);
  errUnwritten(errUnwritten&& from) noexcept
    : errUnwritten() {
    *this = ::std::move(from);
  }

  inline errUnwritten& operator=(const errUnwritten& from) {
    CopyFrom(from);
    return *this;
  }
  inline errUnwritten& operator=(errUnwritten&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const errUnwritten& default_instance() {
    return *internal_default_instance();
  }
  static inline const errUnwritten* internal_default_instance() {
    return reinterpret_cast<const errUnwritten*>(
               &_errUnwritten_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(errUnwritten& a, errUnwritten& b) {
    a.Swap(&b);
  }
  inline void Swap(errUnwritten* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(errUnwritten* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  errUnwritten* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<errUnwritten>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const errUnwritten& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const errUnwritten& from) {
    errUnwritten::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(errUnwritten* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.errUnwritten";
  }
  protected:
  explicit errUnwritten(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrCodeFieldNumber = 1,
  };
  // bool err_code = 1;
  void clear_err_code();
  bool err_code() const;
  void set_err_code(bool value);
  private:
  bool _internal_err_code() const;
  void _internal_set_err_code(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.errUnwritten)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool err_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class errWritten final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.errWritten) */ {
 public:
  inline errWritten() : errWritten(nullptr) {}
  ~errWritten() override;
  explicit PROTOBUF_CONSTEXPR errWritten(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  errWritten(const errWritten& from);
  errWritten(errWritten&& from) noexcept
    : errWritten() {
    *this = ::std::move(from);
  }

  inline errWritten& operator=(const errWritten& from) {
    CopyFrom(from);
    return *this;
  }
  inline errWritten& operator=(errWritten&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const errWritten& default_instance() {
    return *internal_default_instance();
  }
  static inline const errWritten* internal_default_instance() {
    return reinterpret_cast<const errWritten*>(
               &_errWritten_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(errWritten& a, errWritten& b) {
    a.Swap(&b);
  }
  inline void Swap(errWritten* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(errWritten* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  errWritten* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<errWritten>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const errWritten& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const errWritten& from) {
    errWritten::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(errWritten* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.errWritten";
  }
  protected:
  explicit errWritten(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
    kErrCodeFieldNumber = 1,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // bool err_code = 1;
  void clear_err_code();
  bool err_code() const;
  void set_err_code(bool value);
  private:
  bool _internal_err_code() const;
  void _internal_set_err_code(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.errWritten)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    bool err_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class Read final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.Read) */ {
 public:
  inline Read() : Read(nullptr) {}
  ~Read() override;
  explicit PROTOBUF_CONSTEXPR Read(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Read(const Read& from);
  Read(Read&& from) noexcept
    : Read() {
    *this = ::std::move(from);
  }

  inline Read& operator=(const Read& from) {
    CopyFrom(from);
    return *this;
  }
  inline Read& operator=(Read&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Read& default_instance() {
    return *internal_default_instance();
  }
  static inline const Read* internal_default_instance() {
    return reinterpret_cast<const Read*>(
               &_Read_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Read& a, Read& b) {
    a.Swap(&b);
  }
  inline void Swap(Read* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Read* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Read* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Read>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Read& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Read& from) {
    Read::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Read* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.Read";
  }
  protected:
  explicit Read(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.Read)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class Seal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.Seal) */ {
 public:
  inline Seal() : Seal(nullptr) {}
  ~Seal() override;
  explicit PROTOBUF_CONSTEXPR Seal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Seal(const Seal& from);
  Seal(Seal&& from) noexcept
    : Seal() {
    *this = ::std::move(from);
  }

  inline Seal& operator=(const Seal& from) {
    CopyFrom(from);
    return *this;
  }
  inline Seal& operator=(Seal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Seal& default_instance() {
    return *internal_default_instance();
  }
  static inline const Seal* internal_default_instance() {
    return reinterpret_cast<const Seal*>(
               &_Seal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Seal& a, Seal& b) {
    a.Swap(&b);
  }
  inline void Swap(Seal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Seal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Seal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Seal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Seal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Seal& from) {
    Seal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Seal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.Seal";
  }
  protected:
  explicit Seal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHighaddrFieldNumber = 2,
    kSealedFieldNumber = 1,
  };
  // int64 highaddr = 2;
  void clear_highaddr();
  int64_t highaddr() const;
  void set_highaddr(int64_t value);
  private:
  int64_t _internal_highaddr() const;
  void _internal_set_highaddr(int64_t value);
  public:

  // bool sealed = 1;
  void clear_sealed();
  bool sealed() const;
  void set_sealed(bool value);
  private:
  bool _internal_sealed() const;
  void _internal_set_sealed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.Seal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t highaddr_;
    bool sealed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// -------------------------------------------------------------------

class errDeleted final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corfustorage.errDeleted) */ {
 public:
  inline errDeleted() : errDeleted(nullptr) {}
  ~errDeleted() override;
  explicit PROTOBUF_CONSTEXPR errDeleted(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  errDeleted(const errDeleted& from);
  errDeleted(errDeleted&& from) noexcept
    : errDeleted() {
    *this = ::std::move(from);
  }

  inline errDeleted& operator=(const errDeleted& from) {
    CopyFrom(from);
    return *this;
  }
  inline errDeleted& operator=(errDeleted&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const errDeleted& default_instance() {
    return *internal_default_instance();
  }
  static inline const errDeleted* internal_default_instance() {
    return reinterpret_cast<const errDeleted*>(
               &_errDeleted_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(errDeleted& a, errDeleted& b) {
    a.Swap(&b);
  }
  inline void Swap(errDeleted* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(errDeleted* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  errDeleted* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<errDeleted>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const errDeleted& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const errDeleted& from) {
    errDeleted::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(errDeleted* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corfustorage.errDeleted";
  }
  protected:
  explicit errDeleted(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrCodeFieldNumber = 1,
  };
  // bool err_code = 1;
  void clear_err_code();
  bool err_code() const;
  void set_err_code(bool value);
  private:
  bool _internal_err_code() const;
  void _internal_set_err_code(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corfustorage.errDeleted)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool err_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fcorfustorage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Payload

// int64 packet_type = 1;
inline void Payload::clear_packet_type() {
  _impl_.packet_type_ = int64_t{0};
}
inline int64_t Payload::_internal_packet_type() const {
  return _impl_.packet_type_;
}
inline int64_t Payload::packet_type() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.packet_type)
  return _internal_packet_type();
}
inline void Payload::_internal_set_packet_type(int64_t value) {
  
  _impl_.packet_type_ = value;
}
inline void Payload::set_packet_type(int64_t value) {
  _internal_set_packet_type(value);
  // @@protoc_insertion_point(field_set:corfustorage.Payload.packet_type)
}

// optional .corfustorage.Ack ack = 2;
inline bool Payload::_internal_has_ack() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ack_ != nullptr);
  return value;
}
inline bool Payload::has_ack() const {
  return _internal_has_ack();
}
inline void Payload::clear_ack() {
  if (_impl_.ack_ != nullptr) _impl_.ack_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::corfustorage::Ack& Payload::_internal_ack() const {
  const ::corfustorage::Ack* p = _impl_.ack_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::Ack&>(
      ::corfustorage::_Ack_default_instance_);
}
inline const ::corfustorage::Ack& Payload::ack() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.ack)
  return _internal_ack();
}
inline void Payload::unsafe_arena_set_allocated_ack(
    ::corfustorage::Ack* ack) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ack_);
  }
  _impl_.ack_ = ack;
  if (ack) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.ack)
}
inline ::corfustorage::Ack* Payload::release_ack() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfustorage::Ack* temp = _impl_.ack_;
  _impl_.ack_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::Ack* Payload::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.ack)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::corfustorage::Ack* temp = _impl_.ack_;
  _impl_.ack_ = nullptr;
  return temp;
}
inline ::corfustorage::Ack* Payload::_internal_mutable_ack() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.ack_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::Ack>(GetArenaForAllocation());
    _impl_.ack_ = p;
  }
  return _impl_.ack_;
}
inline ::corfustorage::Ack* Payload::mutable_ack() {
  ::corfustorage::Ack* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.ack)
  return _msg;
}
inline void Payload::set_allocated_ack(::corfustorage::Ack* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.ack_;
  }
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(ack);
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ack_ = ack;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.ack)
}

// optional .corfustorage.errSealed err_sealed = 3;
inline bool Payload::_internal_has_err_sealed() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.err_sealed_ != nullptr);
  return value;
}
inline bool Payload::has_err_sealed() const {
  return _internal_has_err_sealed();
}
inline void Payload::clear_err_sealed() {
  if (_impl_.err_sealed_ != nullptr) _impl_.err_sealed_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::corfustorage::errSealed& Payload::_internal_err_sealed() const {
  const ::corfustorage::errSealed* p = _impl_.err_sealed_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::errSealed&>(
      ::corfustorage::_errSealed_default_instance_);
}
inline const ::corfustorage::errSealed& Payload::err_sealed() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.err_sealed)
  return _internal_err_sealed();
}
inline void Payload::unsafe_arena_set_allocated_err_sealed(
    ::corfustorage::errSealed* err_sealed) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.err_sealed_);
  }
  _impl_.err_sealed_ = err_sealed;
  if (err_sealed) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.err_sealed)
}
inline ::corfustorage::errSealed* Payload::release_err_sealed() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::corfustorage::errSealed* temp = _impl_.err_sealed_;
  _impl_.err_sealed_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::errSealed* Payload::unsafe_arena_release_err_sealed() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.err_sealed)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::corfustorage::errSealed* temp = _impl_.err_sealed_;
  _impl_.err_sealed_ = nullptr;
  return temp;
}
inline ::corfustorage::errSealed* Payload::_internal_mutable_err_sealed() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.err_sealed_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::errSealed>(GetArenaForAllocation());
    _impl_.err_sealed_ = p;
  }
  return _impl_.err_sealed_;
}
inline ::corfustorage::errSealed* Payload::mutable_err_sealed() {
  ::corfustorage::errSealed* _msg = _internal_mutable_err_sealed();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.err_sealed)
  return _msg;
}
inline void Payload::set_allocated_err_sealed(::corfustorage::errSealed* err_sealed) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.err_sealed_;
  }
  if (err_sealed) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(err_sealed);
    if (message_arena != submessage_arena) {
      err_sealed = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, err_sealed, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.err_sealed_ = err_sealed;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.err_sealed)
}

// optional .corfustorage.errUnwritten err_unwritten = 4;
inline bool Payload::_internal_has_err_unwritten() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.err_unwritten_ != nullptr);
  return value;
}
inline bool Payload::has_err_unwritten() const {
  return _internal_has_err_unwritten();
}
inline void Payload::clear_err_unwritten() {
  if (_impl_.err_unwritten_ != nullptr) _impl_.err_unwritten_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::corfustorage::errUnwritten& Payload::_internal_err_unwritten() const {
  const ::corfustorage::errUnwritten* p = _impl_.err_unwritten_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::errUnwritten&>(
      ::corfustorage::_errUnwritten_default_instance_);
}
inline const ::corfustorage::errUnwritten& Payload::err_unwritten() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.err_unwritten)
  return _internal_err_unwritten();
}
inline void Payload::unsafe_arena_set_allocated_err_unwritten(
    ::corfustorage::errUnwritten* err_unwritten) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.err_unwritten_);
  }
  _impl_.err_unwritten_ = err_unwritten;
  if (err_unwritten) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.err_unwritten)
}
inline ::corfustorage::errUnwritten* Payload::release_err_unwritten() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::corfustorage::errUnwritten* temp = _impl_.err_unwritten_;
  _impl_.err_unwritten_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::errUnwritten* Payload::unsafe_arena_release_err_unwritten() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.err_unwritten)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::corfustorage::errUnwritten* temp = _impl_.err_unwritten_;
  _impl_.err_unwritten_ = nullptr;
  return temp;
}
inline ::corfustorage::errUnwritten* Payload::_internal_mutable_err_unwritten() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.err_unwritten_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::errUnwritten>(GetArenaForAllocation());
    _impl_.err_unwritten_ = p;
  }
  return _impl_.err_unwritten_;
}
inline ::corfustorage::errUnwritten* Payload::mutable_err_unwritten() {
  ::corfustorage::errUnwritten* _msg = _internal_mutable_err_unwritten();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.err_unwritten)
  return _msg;
}
inline void Payload::set_allocated_err_unwritten(::corfustorage::errUnwritten* err_unwritten) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.err_unwritten_;
  }
  if (err_unwritten) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(err_unwritten);
    if (message_arena != submessage_arena) {
      err_unwritten = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, err_unwritten, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.err_unwritten_ = err_unwritten;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.err_unwritten)
}

// optional .corfustorage.errWritten err_written = 5;
inline bool Payload::_internal_has_err_written() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.err_written_ != nullptr);
  return value;
}
inline bool Payload::has_err_written() const {
  return _internal_has_err_written();
}
inline void Payload::clear_err_written() {
  if (_impl_.err_written_ != nullptr) _impl_.err_written_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::corfustorage::errWritten& Payload::_internal_err_written() const {
  const ::corfustorage::errWritten* p = _impl_.err_written_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::errWritten&>(
      ::corfustorage::_errWritten_default_instance_);
}
inline const ::corfustorage::errWritten& Payload::err_written() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.err_written)
  return _internal_err_written();
}
inline void Payload::unsafe_arena_set_allocated_err_written(
    ::corfustorage::errWritten* err_written) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.err_written_);
  }
  _impl_.err_written_ = err_written;
  if (err_written) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.err_written)
}
inline ::corfustorage::errWritten* Payload::release_err_written() {
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::corfustorage::errWritten* temp = _impl_.err_written_;
  _impl_.err_written_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::errWritten* Payload::unsafe_arena_release_err_written() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.err_written)
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::corfustorage::errWritten* temp = _impl_.err_written_;
  _impl_.err_written_ = nullptr;
  return temp;
}
inline ::corfustorage::errWritten* Payload::_internal_mutable_err_written() {
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.err_written_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::errWritten>(GetArenaForAllocation());
    _impl_.err_written_ = p;
  }
  return _impl_.err_written_;
}
inline ::corfustorage::errWritten* Payload::mutable_err_written() {
  ::corfustorage::errWritten* _msg = _internal_mutable_err_written();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.err_written)
  return _msg;
}
inline void Payload::set_allocated_err_written(::corfustorage::errWritten* err_written) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.err_written_;
  }
  if (err_written) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(err_written);
    if (message_arena != submessage_arena) {
      err_written = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, err_written, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.err_written_ = err_written;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.err_written)
}

// optional .corfustorage.Read read = 6;
inline bool Payload::_internal_has_read() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.read_ != nullptr);
  return value;
}
inline bool Payload::has_read() const {
  return _internal_has_read();
}
inline void Payload::clear_read() {
  if (_impl_.read_ != nullptr) _impl_.read_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::corfustorage::Read& Payload::_internal_read() const {
  const ::corfustorage::Read* p = _impl_.read_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::Read&>(
      ::corfustorage::_Read_default_instance_);
}
inline const ::corfustorage::Read& Payload::read() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.read)
  return _internal_read();
}
inline void Payload::unsafe_arena_set_allocated_read(
    ::corfustorage::Read* read) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.read_);
  }
  _impl_.read_ = read;
  if (read) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.read)
}
inline ::corfustorage::Read* Payload::release_read() {
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::corfustorage::Read* temp = _impl_.read_;
  _impl_.read_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::Read* Payload::unsafe_arena_release_read() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.read)
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::corfustorage::Read* temp = _impl_.read_;
  _impl_.read_ = nullptr;
  return temp;
}
inline ::corfustorage::Read* Payload::_internal_mutable_read() {
  _impl_._has_bits_[0] |= 0x00000010u;
  if (_impl_.read_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::Read>(GetArenaForAllocation());
    _impl_.read_ = p;
  }
  return _impl_.read_;
}
inline ::corfustorage::Read* Payload::mutable_read() {
  ::corfustorage::Read* _msg = _internal_mutable_read();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.read)
  return _msg;
}
inline void Payload::set_allocated_read(::corfustorage::Read* read) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.read_;
  }
  if (read) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(read);
    if (message_arena != submessage_arena) {
      read = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, read, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.read_ = read;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.read)
}

// optional .corfustorage.Seal seal = 7;
inline bool Payload::_internal_has_seal() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.seal_ != nullptr);
  return value;
}
inline bool Payload::has_seal() const {
  return _internal_has_seal();
}
inline void Payload::clear_seal() {
  if (_impl_.seal_ != nullptr) _impl_.seal_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const ::corfustorage::Seal& Payload::_internal_seal() const {
  const ::corfustorage::Seal* p = _impl_.seal_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::Seal&>(
      ::corfustorage::_Seal_default_instance_);
}
inline const ::corfustorage::Seal& Payload::seal() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.seal)
  return _internal_seal();
}
inline void Payload::unsafe_arena_set_allocated_seal(
    ::corfustorage::Seal* seal) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.seal_);
  }
  _impl_.seal_ = seal;
  if (seal) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.seal)
}
inline ::corfustorage::Seal* Payload::release_seal() {
  _impl_._has_bits_[0] &= ~0x00000020u;
  ::corfustorage::Seal* temp = _impl_.seal_;
  _impl_.seal_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::Seal* Payload::unsafe_arena_release_seal() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.seal)
  _impl_._has_bits_[0] &= ~0x00000020u;
  ::corfustorage::Seal* temp = _impl_.seal_;
  _impl_.seal_ = nullptr;
  return temp;
}
inline ::corfustorage::Seal* Payload::_internal_mutable_seal() {
  _impl_._has_bits_[0] |= 0x00000020u;
  if (_impl_.seal_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::Seal>(GetArenaForAllocation());
    _impl_.seal_ = p;
  }
  return _impl_.seal_;
}
inline ::corfustorage::Seal* Payload::mutable_seal() {
  ::corfustorage::Seal* _msg = _internal_mutable_seal();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.seal)
  return _msg;
}
inline void Payload::set_allocated_seal(::corfustorage::Seal* seal) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.seal_;
  }
  if (seal) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(seal);
    if (message_arena != submessage_arena) {
      seal = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, seal, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.seal_ = seal;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.seal)
}

// optional .corfustorage.errDeleted err_deleted = 8;
inline bool Payload::_internal_has_err_deleted() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.err_deleted_ != nullptr);
  return value;
}
inline bool Payload::has_err_deleted() const {
  return _internal_has_err_deleted();
}
inline void Payload::clear_err_deleted() {
  if (_impl_.err_deleted_ != nullptr) _impl_.err_deleted_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const ::corfustorage::errDeleted& Payload::_internal_err_deleted() const {
  const ::corfustorage::errDeleted* p = _impl_.err_deleted_;
  return p != nullptr ? *p : reinterpret_cast<const ::corfustorage::errDeleted&>(
      ::corfustorage::_errDeleted_default_instance_);
}
inline const ::corfustorage::errDeleted& Payload::err_deleted() const {
  // @@protoc_insertion_point(field_get:corfustorage.Payload.err_deleted)
  return _internal_err_deleted();
}
inline void Payload::unsafe_arena_set_allocated_err_deleted(
    ::corfustorage::errDeleted* err_deleted) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.err_deleted_);
  }
  _impl_.err_deleted_ = err_deleted;
  if (err_deleted) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:corfustorage.Payload.err_deleted)
}
inline ::corfustorage::errDeleted* Payload::release_err_deleted() {
  _impl_._has_bits_[0] &= ~0x00000040u;
  ::corfustorage::errDeleted* temp = _impl_.err_deleted_;
  _impl_.err_deleted_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::corfustorage::errDeleted* Payload::unsafe_arena_release_err_deleted() {
  // @@protoc_insertion_point(field_release:corfustorage.Payload.err_deleted)
  _impl_._has_bits_[0] &= ~0x00000040u;
  ::corfustorage::errDeleted* temp = _impl_.err_deleted_;
  _impl_.err_deleted_ = nullptr;
  return temp;
}
inline ::corfustorage::errDeleted* Payload::_internal_mutable_err_deleted() {
  _impl_._has_bits_[0] |= 0x00000040u;
  if (_impl_.err_deleted_ == nullptr) {
    auto* p = CreateMaybeMessage<::corfustorage::errDeleted>(GetArenaForAllocation());
    _impl_.err_deleted_ = p;
  }
  return _impl_.err_deleted_;
}
inline ::corfustorage::errDeleted* Payload::mutable_err_deleted() {
  ::corfustorage::errDeleted* _msg = _internal_mutable_err_deleted();
  // @@protoc_insertion_point(field_mutable:corfustorage.Payload.err_deleted)
  return _msg;
}
inline void Payload::set_allocated_err_deleted(::corfustorage::errDeleted* err_deleted) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.err_deleted_;
  }
  if (err_deleted) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(err_deleted);
    if (message_arena != submessage_arena) {
      err_deleted = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, err_deleted, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.err_deleted_ = err_deleted;
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Payload.err_deleted)
}

// -------------------------------------------------------------------

// Ack

// bool ack_code = 1;
inline void Ack::clear_ack_code() {
  _impl_.ack_code_ = false;
}
inline bool Ack::_internal_ack_code() const {
  return _impl_.ack_code_;
}
inline bool Ack::ack_code() const {
  // @@protoc_insertion_point(field_get:corfustorage.Ack.ack_code)
  return _internal_ack_code();
}
inline void Ack::_internal_set_ack_code(bool value) {
  
  _impl_.ack_code_ = value;
}
inline void Ack::set_ack_code(bool value) {
  _internal_set_ack_code(value);
  // @@protoc_insertion_point(field_set:corfustorage.Ack.ack_code)
}

// -------------------------------------------------------------------

// errSealed

// bool err_code = 1;
inline void errSealed::clear_err_code() {
  _impl_.err_code_ = false;
}
inline bool errSealed::_internal_err_code() const {
  return _impl_.err_code_;
}
inline bool errSealed::err_code() const {
  // @@protoc_insertion_point(field_get:corfustorage.errSealed.err_code)
  return _internal_err_code();
}
inline void errSealed::_internal_set_err_code(bool value) {
  
  _impl_.err_code_ = value;
}
inline void errSealed::set_err_code(bool value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:corfustorage.errSealed.err_code)
}

// -------------------------------------------------------------------

// errUnwritten

// bool err_code = 1;
inline void errUnwritten::clear_err_code() {
  _impl_.err_code_ = false;
}
inline bool errUnwritten::_internal_err_code() const {
  return _impl_.err_code_;
}
inline bool errUnwritten::err_code() const {
  // @@protoc_insertion_point(field_get:corfustorage.errUnwritten.err_code)
  return _internal_err_code();
}
inline void errUnwritten::_internal_set_err_code(bool value) {
  
  _impl_.err_code_ = value;
}
inline void errUnwritten::set_err_code(bool value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:corfustorage.errUnwritten.err_code)
}

// -------------------------------------------------------------------

// errWritten

// bool err_code = 1;
inline void errWritten::clear_err_code() {
  _impl_.err_code_ = false;
}
inline bool errWritten::_internal_err_code() const {
  return _impl_.err_code_;
}
inline bool errWritten::err_code() const {
  // @@protoc_insertion_point(field_get:corfustorage.errWritten.err_code)
  return _internal_err_code();
}
inline void errWritten::_internal_set_err_code(bool value) {
  
  _impl_.err_code_ = value;
}
inline void errWritten::set_err_code(bool value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:corfustorage.errWritten.err_code)
}

// string content = 2;
inline void errWritten::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& errWritten::content() const {
  // @@protoc_insertion_point(field_get:corfustorage.errWritten.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void errWritten::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corfustorage.errWritten.content)
}
inline std::string* errWritten::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:corfustorage.errWritten.content)
  return _s;
}
inline const std::string& errWritten::_internal_content() const {
  return _impl_.content_.Get();
}
inline void errWritten::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* errWritten::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* errWritten::release_content() {
  // @@protoc_insertion_point(field_release:corfustorage.errWritten.content)
  return _impl_.content_.Release();
}
inline void errWritten::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corfustorage.errWritten.content)
}

// -------------------------------------------------------------------

// Read

// string content = 2;
inline void Read::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& Read::content() const {
  // @@protoc_insertion_point(field_get:corfustorage.Read.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Read::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corfustorage.Read.content)
}
inline std::string* Read::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:corfustorage.Read.content)
  return _s;
}
inline const std::string& Read::_internal_content() const {
  return _impl_.content_.Get();
}
inline void Read::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* Read::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* Read::release_content() {
  // @@protoc_insertion_point(field_release:corfustorage.Read.content)
  return _impl_.content_.Release();
}
inline void Read::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corfustorage.Read.content)
}

// -------------------------------------------------------------------

// Seal

// bool sealed = 1;
inline void Seal::clear_sealed() {
  _impl_.sealed_ = false;
}
inline bool Seal::_internal_sealed() const {
  return _impl_.sealed_;
}
inline bool Seal::sealed() const {
  // @@protoc_insertion_point(field_get:corfustorage.Seal.sealed)
  return _internal_sealed();
}
inline void Seal::_internal_set_sealed(bool value) {
  
  _impl_.sealed_ = value;
}
inline void Seal::set_sealed(bool value) {
  _internal_set_sealed(value);
  // @@protoc_insertion_point(field_set:corfustorage.Seal.sealed)
}

// int64 highaddr = 2;
inline void Seal::clear_highaddr() {
  _impl_.highaddr_ = int64_t{0};
}
inline int64_t Seal::_internal_highaddr() const {
  return _impl_.highaddr_;
}
inline int64_t Seal::highaddr() const {
  // @@protoc_insertion_point(field_get:corfustorage.Seal.highaddr)
  return _internal_highaddr();
}
inline void Seal::_internal_set_highaddr(int64_t value) {
  
  _impl_.highaddr_ = value;
}
inline void Seal::set_highaddr(int64_t value) {
  _internal_set_highaddr(value);
  // @@protoc_insertion_point(field_set:corfustorage.Seal.highaddr)
}

// -------------------------------------------------------------------

// errDeleted

// bool err_code = 1;
inline void errDeleted::clear_err_code() {
  _impl_.err_code_ = false;
}
inline bool errDeleted::_internal_err_code() const {
  return _impl_.err_code_;
}
inline bool errDeleted::err_code() const {
  // @@protoc_insertion_point(field_get:corfustorage.errDeleted.err_code)
  return _internal_err_code();
}
inline void errDeleted::_internal_set_err_code(bool value) {
  
  _impl_.err_code_ = value;
}
inline void errDeleted::set_err_code(bool value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:corfustorage.errDeleted.err_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace corfustorage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fcorfustorage_2eproto
