syntax="proto3";

package corfuclient;

message Payload {
    string packet_type = 1;
    optional AppendEntry append = 2;
    optional ReadEntry read = 3;
    optional Trim trim = 4;
    optional Fill fill = 5;
}

message AppendEntry {
   int64 idx = 1;
   string entry = 2;
   int64 currEpoch = 3;
}

message ReadEntry {
    int64 idx = 1;
    string entry = 2;
    int64 currEpoch = 3;
}

message Trim {
    int64 idx = 1;
}

message Fill {
    int64 currEpoch = 1;
    bool junk = 2;
    int64 idx = 3;
}
 
