syntax="proto3";

package corfuclient;

message Payload {
    int64 packet_type = 1;
    int64 clientID = 2;
    int64 threadID = 3;
    optional Append append = 4;
    optional Read read = 5;
    optional Trim trim = 6;
    optional GetToken token_req = 7;
    optional Seal seal = 8;
}

message Append {
   int64 idx = 1;
   string entry = 2;
   int64 currEpoch = 3;
}

message Read {
    int64 idx = 1;
    int64 currEpoch = 2;
}

message Trim {
    int64 idx = 1;
}

message Seal {
    int64 currEpoch = 1;
}

message GetToken {
    bool reqToken = 1;
}