syntax="proto3";

package ringclient;

message Payload {
    int64 packet_type=1;
    int64 nonce=2;
    optional AppendEntry append = 3;
    optional ReadEntry read = 4;
    optional GetTail tail = 5;
    optional Subscribe sub = 6;
    optional Trim trim = 7;
}

message AppendEntry {
   int64 idx=1;
   string entry=2;
}

message ReadEntry {
    int64 idx = 1;
    string entry=2;
}

message GetTail {
    int64 idx = 1;
}

message Subscribe {
    int64 idx = 1;
}

message Trim {
    int64 idx = 1;
}
 
